import Verso
import VersoManual
import VersoBlueprint
import PadicLFunctions
import PadicLFunctionsBlueprint.Refs
import PadicLFunctionsBlueprint.TexPrelude

open Verso.Genre
open Verso.Genre.Manual
open Informal


#doc (Manual) "Overview and roadmap" =>

The formalisation tracks {Informal.citet "RJW"}[] section by section. The notes
split into two parts: Part I constructs the Kubota–Leopoldt $`p`-adic
$`L`-function and pins down its arithmetic, and Part II develops the Iwasawa
theory needed to relate it to ideal class groups, culminating in the Iwasawa Main
Conjecture. Each paper section becomes a blueprint chapter; the bullet lists below
record the headline result of each, which the chapter then expands into nodes.

# Part I — The Kubota–Leopoldt p-adic L-function

The goal of Part I is a single analytic object $`\zeta_p` and a single
interpolation theorem.

- *What a $`p`-adic $`L`-function should be* (§2). The Riemann zeta function
  $`\zeta(s)` has rational special values $`\zeta(1-n) = -B_n/n`. After removing
  the Euler factor at $`p`, the values $`(1 - p^{n-1})\zeta(1-n)` satisfy Kummer's
  congruences modulo powers of $`p`, which is exactly the statement that they
  extend to a continuous (indeed analytic) function on $`\Zp` — the $`p`-adic
  $`L`-function. This chapter fixes the interpolation property we are aiming for.

- *Measures and the Iwasawa algebra* (§3). A $`p`-adic measure on $`\Zp` is a
  bounded $`\Cp`-linear functional on continuous functions; the Mahler transform
  identifies measures with power series, giving the ring isomorphism
  $`\Lam := \Zp[[\Zpx]] \cong \Zp[[T]]` (the Iwasawa algebra). This is the
  foundational chapter: measures, the Iwasawa algebra, Mahler transforms, the
  measure-theoretic toolbox, pseudo-measures, and locally analytic distributions.

- *Construction of $`\zeta_p`* (§4). Following Kubota–Leopoldt, one writes down,
  for $`a` coprime to $`p`, an explicit measure $`\mu_a` on $`\Zp`, restricts it
  to $`\Zpx`, and rescales away the dependence on $`a` to obtain the pseudo-measure
  whose Mellin transform is the Kubota–Leopoldt $`p`-adic $`L`-function.

- *Interpolation at Dirichlet characters* (§5). Integrating $`\zeta_p` against a
  Dirichlet character $`\chi` of $`p`-power conductor — and then against tame
  conductors — recovers, up to explicit Euler and Gauss-sum factors, the special
  values $`L(\chi, 1-n)` of the complex Dirichlet $`L`-function. The Mellin
  transform turns measures on $`\Zpx` into analytic functions on $`\Zp`.

- *The value at $`s=1`* (§6) and *the residue at $`s=1`* (§7). The $`p`-adic
  analytic class number formula: $`\zeta_p` has a simple pole at $`s=1` whose
  residue is the $`p`-adic analogue of $`1 - 1/p`, mirroring the complex residue
  of $`\zeta`.

- *The $`p`-adic family of Eisenstein series* (§8). The constant terms of a
  $`p`-adic family of Eisenstein series are values of $`\zeta_p`, foreshadowing the
  modular-forms picture of Part II.

# Part II — Iwasawa theory and the Main Conjecture

Part II reinterprets $`\zeta_p` as an element of the Iwasawa algebra and matches
it against arithmetic.

- *The Coleman map* (§9–§10). Coleman's theorem on norm-coherent systems of units
  in the cyclotomic tower {Informal.citet "coleman"}[] produces a map from local
  units to the Iwasawa algebra; applied to cyclotomic units it manufactures the
  $`p`-adic $`L`-function on the algebraic side.

- *Iwasawa's theorem on the zeros of $`\zeta_p`* (§11–§12). Measures on the Galois
  group $`\Gal(\Q(\mu_{p^\infty})/\Q)`, the equivariance of the Coleman map, the
  fundamental exact sequence, and explicit generators for global and local
  cyclotomic units combine to identify the ideal generated by $`\zeta_p`.

- *The Iwasawa Main Conjecture* (§13). With the structure theory of finitely
  generated $`\Lam`-modules in hand, the Main Conjecture equates the
  characteristic ideal of a certain Galois module with the ideal generated by
  $`\zeta_p`. We follow the notes' proof for Vandiver primes.

- *Iwasawa's $`\mu`-invariant* (§14) and *Iwasawa theory for modular forms*
  (§15). The $`\mu = 0` theorem and its consequences, then the $`\mathrm{GL}(2)`
  analogue that recasts the whole story for modular forms.

The chapters that follow this overview are populated by `/develop` and
`/blueprint` as the formalisation proceeds.
