import Verso
import VersoManual
import VersoBlueprint
import PadicLFunctions
import PadicLFunctionsBlueprint.Refs
import PadicLFunctionsBlueprint.TexPrelude

open Verso.Genre
open Verso.Genre.Manual
open Informal


#doc (Manual) "The Iwasawa Main Conjecture" =>

We now move from arithmetic to algebra. To state the Iwasawa Main Conjecture we
use the structure theory of $`\Lam`-modules. We first summarise that theory, then
introduce the $`\Lam`-modules coming from the Galois theory of abelian extensions.
These modules carry an action of the Galois group
$`\GG = \Gal(F_\infty/\Q) \cong \Zpx`, and so become $`\Lam(\GG)`-modules. The
Main Conjecture describes the *characteristic ideal* of one of these Galois
modules in terms of the Kubota–Leopoldt $`p`-adic $`L`-function $`\zeta_p`.

Throughout, $`p` is an odd prime, $`L/\Qp` is a finite extension with ring of
integers $`\cO_L` and maximal ideal $`\mathfrak{p}`, and
$`\Lam = \Lam(\Zp) = \varprojlim_n \cO_L[\Zp/p^n\Zp] \cong \cO_L[[T]]` is the
Iwasawa algebra of $`\Zp` over $`\cO_L`. We write $`F_n = \Q(\mu_{p^n})` and
$`F_n^+` for its maximal totally real subfield, $`F_\infty = \cup_n F_n`,
$`F_\infty^+ = \cup_n F_n^+`, and $`\GG^+ = \Gal(F_\infty^+/\Q)`.

# Structure theory for Lambda-modules

There is a rich structure theory for modules over Iwasawa algebras, closely
mirroring the theory of modules over a PID. We state the basic results without
proof.

:::definition "imc-pseudo-isomorphism"
Let $`M, M'` be two $`\Lam`-modules. We say $`M` is *pseudo-isomorphic* to $`M'`,
written $`M \sim M'`, if there is a homomorphism $`M \to M'` with finite kernel
and cokernel, equivalently an exact sequence
$$`0 \to A \to M \to M' \to B \to 0`
with $`A` and $`B` finite (i.e.\ of finite cardinality). The relation $`\sim` is
*not* symmetric in general, but it *is* an equivalence relation on the class of
finitely generated torsion $`\Lam`-modules.
:::

:::definition "imc-distinguished-polynomial"
A polynomial $`P(T) \in \cO_L[T]` is *distinguished* if it is monic of the form
$`P(T) = T^n + a_{n-1}T^{n-1} + \cdots + a_1 T + a_0` with every $`a_i \in \mathfrak{p}`
for $`0 \le i \le n-1`.
:::

:::theorem "lambda-module-structure"
Let $`M` be a finitely generated $`\Lam`-module. Then $`M` is pseudo-isomorphic
to a direct sum
$$`M \sim \Lam^r \oplus \Big( \bigoplus_{i=1}^s \Lam/(p^{n_i}) \Big) \oplus \Big( \bigoplus_{j=1}^t \Lam/(f_j(T)^{m_j}) \Big),`
for some integers $`r,s,t \ge 0`, exponents $`n_i, m_j \ge 1`, and irreducible
distinguished polynomials $`f_j(T) \in \cO_L[T]`. This rests on
{uses "imc-pseudo-isomorphism"}[] and {uses "imc-distinguished-polynomial"}[].
:::

:::proof "lambda-module-structure"
This is the structure theorem of {Informal.citet "washington"}[]. The Iwasawa
algebra $`\Lam \cong \cO_L[[T]]` is a complete regular local ring of Krull
dimension $`2` which, while not a PID, is a unique factorisation domain whose
height-one primes are $`(p)` and the ideals $`(f)` generated by irreducible
distinguished polynomials (by the Weierstrass preparation theorem every nonzero
element is, up to a unit, $`p^\mu` times a distinguished polynomial). Localising
$`M` at each height-one prime reduces to the principal-ideal situation, and
patching the resulting elementary divisors over all height-one primes yields the
displayed pseudo-isomorphism; the discrepancy supported at the maximal ideal is
exactly the finite kernel and cokernel allowed by $`\sim`.
:::

It is essential that this holds only for the *projective limit* $`\Lam`, and not
for the finite-level group algebras $`\cO_L[\Zp/p^n\Zp]`. This is a recurring
theme of Iwasawa theory: one studies the whole tower of objects at once rather
than each finite layer individually.

:::definition "characteristic-ideal"
Let $`M` be a *finitely generated torsion* $`\Lam`-module, so that $`r = 0` in
the structure theorem {bpref "lambda-module-structure"}[]. The *characteristic
ideal* of $`M` is
$$`\Ch_{\Lam}(M) = (p^{n}) \prod_{j=1}^t (f_j^{m_j}) \subseteq \Lam, \qquad n = \sum_{i=1}^s n_i.`
Equivalently, $`\Ch_\Lam(M)` is the principal ideal generated by a generator of
the product of the height-one elementary divisors.
:::

We will apply this theory in a slightly more general setting. Suppose
$`\GG = H \times \Gamma'`, where $`H` is a finite commutative group of order
prime to $`p` and $`\Gamma' \cong \Zp`; the key example is $`\GG = \Zpx`,
$`H = \mu_{p-1}`, $`\Gamma' = 1 + p\Zp`. Then
$$`\Lam(\GG) \cong \cO_L[H] \otimes_{\cO_L} \Lam.`
For each character $`\omega` of $`H` (possibly after enlarging $`L` to contain its
values) define the idempotent projector
$$`e_\omega = \frac{1}{|H|} \sum_{a \in H} \omega^{-1}(a)\,[a] \in \cO_L[H],`
which makes sense because $`|H|` is invertible in $`\cO_L`.

:::lemma_ "imc-isotypic-decomposition"
Let $`M` be a finitely generated torsion $`\Lam(\GG)`-module. The group $`H` acts
on $`M^{(\omega)} := e_\omega M` through the character $`\omega`, and there is a
decomposition of $`\Lam(\GG)`-modules
$$`M = \bigoplus_{\omega \in H^\wedge} M^{(\omega)}.`
Moreover each $`M^{(\omega)}` is a finitely generated torsion $`\Lam`-module.
:::

:::proof "imc-isotypic-decomposition"
Since $`|H|` is a unit in $`\cO_L`, the idempotents $`e_\omega` are orthogonal and
sum to $`1` in $`\cO_L[H]`, so they decompose any $`\cO_L[H]`-module into its
$`\omega`-isotypic pieces; this is just the semisimplicity of the group algebra of
a prime-to-$`p` group over a ring in which its order is invertible. The
decomposition is $`\Lam(\GG)`-linear because the $`e_\omega` are central. Each
summand is cut out by an idempotent from a finitely generated torsion module, so
is itself finitely generated and torsion over $`\Lam`.
:::

:::definition "imc-characteristic-ideal-general"
With $`\GG = H \times \Gamma'` as above and $`M` a finitely generated torsion
$`\Lam(\GG)`-module, the *characteristic ideal* of $`M` is
$$`\Ch_{\Lam(\GG)}(M) := \bigoplus_{\omega \in H^\wedge} \Ch_{\Lam}\big(M^{(\omega)}\big) \subseteq \Lam(\GG),`
using the isotypic decomposition {uses "imc-isotypic-decomposition"}[] and the
characteristic ideal {uses "characteristic-ideal"}[] of each $`\Lam`-component.
:::

:::lemma_ "imc-char-ideal-multiplicative"
The characteristic ideal is multiplicative in short exact sequences: if
$`0 \to M' \to M \to M'' \to 0` is an exact sequence of finitely generated torsion
$`\Lam(\GG)`-modules, then
$`\Ch_{\Lam(\GG)}(M) = \Ch_{\Lam(\GG)}(M')\cdot \Ch_{\Lam(\GG)}(M'')`. This uses
{uses "imc-characteristic-ideal-general"}[].
:::

:::proof "imc-char-ideal-multiplicative"
Reduce to the case of $`\Lam`-modules via the isotypic decomposition
{uses "imc-isotypic-decomposition"}[], which is exact. For $`\Lam`-modules one
localises at each height-one prime $`\mathfrak{q}`: the localisation $`\Lam_\mathfrak{q}`
is a discrete valuation ring, and over a DVR length is additive in short exact
sequences. Hence the $`\mathfrak{q}`-adic exponent of the characteristic ideal —
the length of $`M_\mathfrak{q}` — is the sum of those of $`M'` and $`M''`, which is
exactly multiplicativity of the ideals.
:::

# The Lambda-modules arising from Galois theory

The following $`\Lam`-modules are the protagonists on the Galois side of the Main
Conjecture. Recall that $`\mathfrak{p}_n` is the unique prime above $`p` in
$`F_n`, and $`\mathfrak{p}_n^+` the unique prime above $`p` in $`F_n^+`.

:::definition "imc-galois-extensions"
For each $`n \ge 1` define
$$`\sM_n = \text{maximal abelian } p\text{-extension of } F_n \text{ unramified outside } \mathfrak{p}_n,`
$$`\sL_n = \text{maximal unramified abelian } p\text{-extension of } F_n,`
and analogously $`\sM_n^+, \sL_n^+` over $`F_n^+` (unramified outside
$`\mathfrak{p}_n^+`). Passing to the limit,
$$`\sM_\infty = \bigcup_n \sM_n, \quad \sL_\infty = \bigcup_n \sL_n, \quad \sM_\infty^+ = \bigcup_n \sM_n^+, \quad \sL_\infty^+ = \bigcup_n \sL_n^+,`
so that $`\sM_\infty` is the maximal abelian pro-$`p`-extension of $`F_\infty`
unramified outside $`\mathfrak{p}`, and $`\sL_\infty` is the maximal unramified
abelian pro-$`p`-extension of $`F_\infty`.
:::

:::definition "imc-galois-modules"
Define the Galois groups
$$`\sX_\infty = \Gal(\sM_\infty/F_\infty), \qquad \sX_\infty^+ = \Gal(\sM_\infty^+/F_\infty^+),`
$$`\sY_\infty = \Gal(\sL_\infty/F_\infty), \qquad \sY_\infty^+ = \Gal(\sL_\infty^+/F_\infty^+),`
using the extensions of {uses "imc-galois-extensions"}[]. By construction the
fields sit in towers $`F_n \subseteq \sL_n \subseteq \sM_n` and
$`F_\infty \subseteq \sL_\infty \subseteq \sM_\infty` (and likewise with the
$`{}^+` superscripts), so $`\sY_\infty = \Gal(\sL_\infty/F_\infty)` is a quotient
of $`\sX_\infty = \Gal(\sM_\infty/F_\infty)`. The modules
$`\sX_\infty^+, \sY_\infty^+` are the analogous Galois groups over the totally real
tower $`F_\infty^+`.
:::

:::definition "imc-galois-action"
The modules $`\sX_\infty, \sY_\infty` are $`\Lam(\GG)`-modules, and
$`\sX_\infty^+, \sY_\infty^+` are $`\Lam(\GG^+)`-modules. For $`x \in \sX_\infty`
and $`\sigma \in \GG`, lift $`\sigma` to any
$`\tilde\sigma \in \Gal(\sM_\infty/\Q)` and set
$$`\sigma \cdot x := \tilde\sigma\, x\, \tilde\sigma^{-1}.`
This is well defined because $`\sX_\infty` is abelian, so the conjugation is
independent of the lift. Since $`\cO_L[\GG]` is dense in the Hausdorff ring
$`\Lam(\GG)`, the action extends by $`\cO_L`-linearity and continuity to all of
$`\Lam(\GG)`. The actions on $`\sY_\infty`, $`\sX_\infty^+`, $`\sY_\infty^+` are
defined identically. This refers to {uses "imc-galois-modules"}[] and the Iwasawa
algebra {uses "iwasawa-algebra"}[].
:::

# The Main Conjecture

Recall the ideal $`I(\GG^+)\zeta_p \subseteq \Lam(\GG^+)` generated by the
Kubota–Leopoldt pseudo-measure — concretely the topological ideal generated by the
elements $`([g]-[1])\zeta_p`, $`g \in \GG^+`. It encodes the zeros of $`\zeta_p`,
and Iwasawa's theorem already gave it an arithmetic description in terms of
cyclotomic units. The Main Conjecture upgrades this to a statement about the
Galois module $`\sX_\infty^+`.

:::theorem "iwasawa-main-conjecture"
*(Iwasawa Main Conjecture.)* The module $`\sX_\infty^+` is a finitely generated
torsion $`\Lam(\GG^+)`-module, and its characteristic ideal equals the ideal of
$`\zeta_p`:
$$`\Ch_{\Lam(\GG^+)}(\sX_\infty^+) = I(\GG^+)\,\zeta_p.`
This is a statement about {uses "characteristic-ideal"}[] of the Galois module
{uses "imc-galois-modules"}[] and the ideal {uses "ideal-of-zeta-p"}[] generated
by the Kubota–Leopoldt $`p`-adic $`L`-function {uses "kubota-leopoldt"}[].
:::

:::proof "iwasawa-main-conjecture"
For Vandiver primes this follows from the explicit isomorphism
{uses "imc-vandiver"}[], which gives
$`\sX_\infty^+ \cong \Lam(\GG^+)/I(\GG^+)\zeta_p`; taking characteristic ideals of
both sides and using that $`\Ch_{\Lam(\GG^+)}(\Lam(\GG^+)/J) = J` for an ideal
$`J` cut out by elementary divisors yields the claim. The conjecture holds
unconditionally by the theorem of Mazur–Wiles (and, via Euler systems, by
Kolyvagin–Rubin–Thaine); in these notes we prove only the Vandiver case.
:::

It is traditional to phrase the Main Conjecture in terms of an *even* Dirichlet
character of $`\Gal(\Q(\mu_p)/\Q)`. The parity of the character produces the
familiar even/odd dichotomy (visible already in the Bernoulli numbers); the
formulation above packages together all even characters. For the odd case one
works with $`\sY_\infty^+` instead.

# The Iwasawa Main Conjecture for Vandiver primes

:::definition "imc-vandiver-prime"
Let $`h_n^+ = \#\Cl(F_n^+)` be the class number of $`F_n^+`. The prime $`p` is a
*Vandiver prime* if $`p \nmid h_1^+`.
:::

We sketch Iwasawa's conditional proof, following the exposition of
Coates–Sujatha. We freely use class field theory and some classical results whose
proofs we omit.

:::definition "imc-unit-modules"
For $`n \ge 1` let $`\sE_n` be the $`p`-adic closure of the global units
$`\sV_n = \cO_{F_n}^\times` inside the local units $`\sU_n`, put
$`\sE_n^+ = \sE_n \cap \sU_n^+`, and set
$$`\sE_{n,1} = \sE_n \cap \sU_{n,1}, \qquad \sE_{n,1}^+ = \sE_n^+ \cap \sU_{n,1},`
$$`\sE_{\infty,1} = \varprojlim_n \sE_{n,1}, \qquad \sE_{\infty,1}^+ = \varprojlim_n \sE_{n,1}^+,`
where $`\sU_{n,1}` denotes the local units congruent to $`1` modulo
$`\mathfrak{p}_n`.
:::

Leopoldt's conjecture, known here by a theorem of Brumer, asserts that $`\sE_n` is
a $`\Zp`-module of rank $`r_1 + r_2 - 1 = p^{n-1}(p-1)/2`; equivalently, global
units that are multiplicatively $`\Z`-independent remain $`\Zp`-independent.

:::proposition "imc-cft-units-1"
There is an exact sequence of $`\Lam(\GG^+)`-modules
$$`0 \to \sE_{\infty,1}^+ \to \sU_{\infty,1}^+ \to \Gal(\sM_\infty^+/\sL_\infty^+) \to 0.`
This uses the unit modules {uses "imc-unit-modules"}[] and the Galois extensions
{uses "imc-galois-extensions"}[].
:::

:::proof "imc-cft-units-1"
Global class field theory identifies, at each finite level $`n`, the Galois group
$`\Gal(\sM_n^+/\sL_n^+)` with the quotient of the local units modulo the closure
of the global units, giving a short exact sequence
$$`0 \to \sE_{n,1}^+ \to \sU_{n,1}^+ \to \Gal(\sM_n^+/\sL_n^+) \to 0.`
All three terms are finitely generated $`\Zp`-modules, so the inverse system
satisfies the Mittag-Leffler condition and $`\varprojlim_n` is exact; taking the
limit over $`n` gives the stated sequence.
:::

:::corollary "imc-cft-units-2"
There is an exact sequence of $`\Lam(\GG^+)`-modules
$$`0 \to \sE_{\infty,1}^+/\sC_{\infty,1}^+ \to \sU_{\infty,1}^+/\sC_{\infty,1}^+ \to \sX_\infty^+ \to \sY_\infty^+ \to 0,`
where $`\sC_{\infty,1}^+` is the module of cyclotomic units. This rests on
{uses "imc-cft-units-1"}[] and {uses "cyclotomic-units"}[].
:::

:::proof "imc-cft-units-2"
The fundamental theorem of Galois theory gives a short exact sequence
$$`0 \to \Gal(\sM_\infty^+/\sL_\infty^+) \to \sX_\infty^+ \to \sY_\infty^+ \to 0,`
since $`F_\infty^+ \subseteq \sL_\infty^+ \subseteq \sM_\infty^+`. Splice this with
the sequence of {uses "imc-cft-units-1"}[], identifying the kernel term
$`\Gal(\sM_\infty^+/\sL_\infty^+) \cong \sU_{\infty,1}^+/\sE_{\infty,1}^+`. Dividing
numerator and denominator by the cyclotomic units $`\sC_{\infty,1}^+ \subseteq \sE_{\infty,1}^+`
and applying the third isomorphism theorem rewrites this as
$`(\sU_{\infty,1}^+/\sC_{\infty,1}^+)\big/(\sE_{\infty,1}^+/\sC_{\infty,1}^+)`,
yielding the four-term exact sequence.
:::

The remaining input is a result from classical Iwasawa theory relating the
coinvariants of $`\sY_\infty^+` to finite-level class groups. Set
$$`\sY_n^+ = \Gal(\sL_n^+/F_n^+) \cong \Cl(F_n^+)\otimes_\Z \Zp.`

:::proposition "imc-coinvariants"
For all $`n \ge 0`, the module of coinvariants of $`\sY_\infty^+` under
$`\GG_n^+ = \Gal(F_\infty^+/F_n^+)` is
$$`(\sY_\infty^+)_{\GG_n^+} = \sY_n^+.`
This refers to {uses "imc-galois-modules"}[].
:::

:::proof "imc-coinvariants"
This is a standard fact of Iwasawa theory (proved in the appendix on the
$`\mu`-invariant). The unramified pro-$`p` tower $`\sL_\infty^+/F_\infty^+`
descends layer by layer: taking $`\GG_n^+`-coinvariants of
$`\sY_\infty^+ = \Gal(\sL_\infty^+/F_\infty^+)` recovers the Galois group of the
maximal unramified abelian $`p`-extension of $`F_n^+` that is split over the
tower, which by class field theory is the $`p`-part of the class group, i.e.\
$`\sY_n^+`. See {uses "mu-invariant"}[].
:::

:::corollary "imc-vandiver-consequences"
If $`p` is a Vandiver prime, then
*(i)* $`\sY_\infty^+ = 0`; *(ii)* $`p \nmid h_n^+` for every $`n \ge 1`; and
*(iii)* $`\sE_{\infty,1}^+/\sC_{\infty,1}^+ = 0`. This uses
{uses "imc-vandiver-prime"}[], {uses "imc-coinvariants"}[] and
{uses "cyclotomic-units"}[].
:::

:::proof "imc-vandiver-consequences"
By the displayed isomorphism $`\sY_n^+ \cong \Cl(F_n^+)\otimes_\Z\Zp`, the
condition $`p \nmid h_n^+` is equivalent to $`\sY_n^+ = 0`.

*(i)* If $`p \nmid h_1^+` then $`(\sY_\infty^+)_{\GG_0^+} = \sY_1^+ = 0` by
{uses "imc-coinvariants"}[]. Since $`\sY_\infty^+` is a finitely generated
$`\Lam(\GG^+)`-module whose coinvariants vanish, Nakayama's lemma forces
$`\sY_\infty^+ = 0`.

*(ii)* Vanishing of $`\sY_\infty^+` and {uses "imc-coinvariants"}[] give
$`\sY_n^+ = 0` for all $`n`, i.e.\ $`p \nmid h_n^+`.

*(iii)* The classical class-number formula gives
$`[\sV_n^+ : \sD_n^+] = h_n^+`, which is prime to $`p` by (ii); the isomorphism
theorem $`S/(S\cap N) \cong SN/N` shows $`[\sV_{n,1}^+ : \sD_{n,1}^+]` divides
$`h_n^+`, so is also prime to $`p`. Hence $`\sV_{n,1}^+/\sD_{n,1}^+` is finite of
order prime to $`p`, and tensoring the sequence
$`0 \to \sD_{n,1}^+ \to \sV_{n,1}^+ \to W_n \to 0` with $`\Zp` kills $`W_n`, giving
$`\sD_{n,1}^+\otimes_\Z\Zp \cong \sV_{n,1}^+\otimes_\Z\Zp`. As $`\sC_{n,1}^+`
(resp.\ $`\sE_{n,1}^+`) is the $`p`-adic closure of $`\sD_{n,1}^+` (resp.\
$`\sV_{n,1}^+`), the surjections
$`\sD_{n,1}^+\otimes_\Z\Zp \twoheadrightarrow \sC_{n,1}^+` and
$`\sV_{n,1}^+\otimes_\Z\Zp \twoheadrightarrow \sE_{n,1}^+` make the inclusion
$`\sC_{n,1}^+ \hookrightarrow \sE_{n,1}^+` surjective, hence an isomorphism.
Passing to the limit gives $`\sC_{\infty,1}^+ \cong \sE_{\infty,1}^+`.
:::

:::theorem "imc-vandiver"
If $`p` is a Vandiver prime, then there is an isomorphism of
$`\Lam(\GG^+)`-modules
$$`\sX_\infty^+ \cong \Lam(\GG^+)/I(\GG^+)\zeta_p.`
In particular the Iwasawa Main Conjecture {uses "iwasawa-main-conjecture"}[]
holds. This combines {uses "imc-cft-units-2"}[], {uses "imc-vandiver-consequences"}[]
and {uses "iwasawa-zeros-theorem"}[].
:::

:::proof "imc-vandiver"
Insert the Vandiver vanishing {uses "imc-vandiver-consequences"}[] (i) and (iii)
into the exact sequence {uses "imc-cft-units-2"}[]: the outer terms
$`\sE_{\infty,1}^+/\sC_{\infty,1}^+` and $`\sY_\infty^+` both vanish, collapsing the
four-term sequence to an isomorphism
$`\sU_{\infty,1}^+/\sC_{\infty,1}^+ \xrightarrow{\sim} \sX_\infty^+`. Iwasawa's
theorem {uses "iwasawa-zeros-theorem"}[] identifies the left-hand side with
$`\Lam(\GG^+)/I(\GG^+)\zeta_p`, giving the displayed isomorphism. Taking
characteristic ideals then proves the Main Conjecture in this case.
:::

Conjecturally every prime is a Vandiver prime, so conjecturally the argument above
proves the full Main Conjecture. This conditional proof is due to Iwasawa himself;
the first unconditional proof was given by Mazur–Wiles, and a later proof using
Euler systems is due to Kolyvagin, Rubin and Thaine.

# Generalisations: Selmer groups and the Iwasawa–Greenberg Main Conjecture

We conclude with a sketch of Greenberg's formulation of a Main Conjecture for
general Galois representations, which recovers the classical statement for the
trivial representation. The objects on the algebraic side are *Selmer groups*. We
work over $`\cF = F_\infty^+ = \Q(\mu_{p^\infty})^+`, with coefficients in a fixed
finite extension $`L/\Qp`.

:::definition "imc-selmer-group"
Let $`M` be a topological $`\cO_L`-module with a continuous $`\cO_L`-linear action
of $`\GG_\cF = \Gal(\overline{\cF}/\cF)`, unramified outside a finite set of
places. A *Selmer structure* $`\cL = (\cL_v)_v` for $`M` is a choice of subspace
$`\cL_v \subseteq H^1(\cF_v, M)` for every finite place $`v` of $`\cF`, with
$`\cL_v = H^1_{\mathrm{ur}}(\cF_v, M)` for almost all $`v`, where the *unramified*
subgroup is $`H^1_{\mathrm{ur}}(\cF_v, M) = \ker\big(H^1(\cF_v, M) \to H^1(I_{\cF_v}, M)\big)`
with $`I_{\cF_v}` the inertia group. The associated *Selmer group* is
$$`H^1_{\cL}(\cF, M) = \ker\Big( H^1(\cF, M) \to \bigoplus_v H^1(\cF_v, M)/\cL_v \Big),`
the sum over all finite places $`v`.
:::

We take $`T` a finite free $`\Zp`-module with a $`\GG_\Q`-action attached to some
arithmetic object, set $`V = T\otimes_{\Zp}\Qp` and $`W = V/T \cong V\otimes(\Qp/\Zp)`,
and take $`M = W`. Away from $`p` we always impose the unramified local condition;
at $`p` there are two standard prescriptions.

:::definition "imc-selmer-at-p"
With $`\cF = \Q(\mu_{p^\infty})^+` and $`v_p` the unique place of $`\cF` above
$`p`:
*(Greenberg)* Assume $`V` is $`p`-*ordinary*: there is a saturated finite
$`\GG_\Q`-stable filtration $`\Fil^\bullet V` on which the inertia group
$`I_{\Qp}` acts on $`\Fil^i/\Fil^{i+1}` through the $`i`-th power of the cyclotomic
character. Then
$$`\cL_{v_p}^{\Gr} = \ker\Big( H^1(\cF_{v_p}, W) \to H^1(I_{v_p}, W) \to H^1(I_{v_p}, W/\Fil^1 W) \Big),`
where $`\Fil^1 W` is the image of $`\Fil^1 V` in $`W`.
*(Bloch–Kato)* Using $`p`-adic Hodge theory and Fontaine's ring $`\Bcris` of
crystalline periods, set $`H^1_f(\cF_{v_p}, V) = \ker\big(H^1(\cF_{v_p}, V) \to H^1(\cF_{v_p}, V\otimes\Bcris)\big)`
and $`\cL_{v_p}^{\mathrm{BK}} = \Im\big(H^1_f(\cF_{v_p}, V) \to H^1(\cF_{v_p}, W)\big)`.
This refines the Selmer structure of {uses "imc-selmer-group"}[].
:::

The two prescriptions agree in many fundamental cases. We now reinterpret
$`\sX_\infty^+` as a Greenberg Selmer group for the cyclotomic twists
$`W_n = (\Qp/\Zp)(n)`.

:::proposition "imc-selmer-equals-X"
Let $`n` be even and positive. With $`T_n = \Zp(n)`, $`V_n = \Qp(n)`,
$`W_n = V_n/T_n` and the Greenberg local conditions of {uses "imc-selmer-at-p"}[],
the Selmer group over $`\cF = F_\infty^+` is
$$`H^1_{\cL^{\Gr}}(F_\infty, W_n) = \Hom_{\mathrm{cts}}(\sX_\infty^+, W_n),`
a twist of the Pontryagin dual of the module $`\sX_\infty^+` of the Main
Conjecture. This uses {uses "imc-galois-modules"}[] and {uses "imc-galois-action"}[].
:::

:::proof "imc-selmer-equals-X"
Since $`\GG_{F_\infty}` acts trivially on $`W_n`, cohomology classes are continuous
homomorphisms: $`H^1(F_\infty, W_n) = \Hom_{\mathrm{cts}}(\GG_{F_\infty}, W_n)`.
As $`\Gal(F_\infty/F_\infty^+) = \{1, c\} \cong \{\pm 1\}` and $`p` is odd,
inflation–restriction gives
$`H^1(\cF, W_n) = \Hom_{\mathrm{cts}, \{\pm1\}}(\GG_{F_\infty}, W_n)`, the
$`\{\pm1\}`-equivariant homomorphisms (the $`\GG`-action being conjugation as in
{uses "imc-galois-action"}[]). Imposing the unramified condition at all $`v \nmid p`
factors such a homomorphism through
$`\sX_\infty = \Gal(\sM_\infty/F_\infty)`. At $`p`, the Greenberg filtration
$`\Fil^i\Qp(n) = \Qp(n)` for $`i \le n` and $`0` otherwise makes the local
condition $`\cL_{v_p}^{\Gr}` empty when $`n \ge 1`, so no further constraint is
imposed and the class descends to $`\sX_\infty`. Finally $`c` acts on $`W_n` by
$`(-1)^n`, so for even $`n>0` only the $`c=+1` part survives:
$`H^1_{\cL^{\Gr}}(F_\infty, W_n) = \Hom_{\mathrm{cts}}((\sX_\infty)^{c=1}, W_n)`. The
natural surjection $`\sX_\infty \twoheadrightarrow \sX_\infty^+` induces
$`(\sX_\infty)^{c=1} \cong \sX_\infty^+`, giving the stated identification with
$`\Hom_{\mathrm{cts}}(\sX_\infty^+, W_n)`. For $`n \le 0` the same analysis adds the
unramified condition at $`p`, replacing $`\sX_\infty` by $`\sY_\infty`.
:::

:::theorem "imc-greenberg-conjecture"
*(Iwasawa–Greenberg Main Conjecture, conjectural.)* Let $`V` be $`p`-ordinary with
Tate dual $`V^\vee = \Hom_{\mathrm{cts}}(V, \Qp(1))`,
let $`L_\infty(V,s)` be the Gamma factor of $`V` (a zero-free product of translates
of $`\Gamma(s)`), and let $`r_V` be the order of the pole of $`L_\infty(V,s)` at
$`s=1`. Then:
*(i)* $`H^1_{\cL^{\Gr}}(\cF, W)` has $`\Lam(\Gamma^+)`-corank equal to $`r_V`.
*(ii)* If $`r_V = r_{V^\vee} = 0`, the characteristic ideal of the Pontryagin dual
of $`H^1_{\cL^{\Gr}}(\cF, W)` equals the ideal generated by the conjectural
$`p`-adic $`L`-function of $`V` (an element of the fraction field of
$`\Lam(\Gamma^+)`, predicted by Coates–Perrin-Riou). This generalises
{uses "iwasawa-main-conjecture"}[] and refers to {uses "imc-selmer-group"}[],
{uses "imc-selmer-at-p"}[] and {uses "characteristic-ideal"}[].
:::

:::proof "imc-greenberg-conjecture"
This is a conjecture, recorded here for context; we only indicate why it recovers
the classical case. For even $`n > 0` the Selmer group is
$`\Hom_{\mathrm{cts}}(\sX_\infty^+, W_n)` by {uses "imc-selmer-equals-X"}[], whose
Pontryagin dual is $`\sX_\infty^+(-n)`, the twist of $`\sX_\infty^+` by
$`\chi^{-n}`. In this case Greenberg's $`p`-adic $`L`-function is $`\partial^n\zeta_p`,
the $`n`-th twist of Kubota–Leopoldt {uses "kubota-leopoldt"}[], so part (ii)
becomes a twist of the Iwasawa Main Conjecture {uses "iwasawa-main-conjecture"}[].
Strictly the case $`n=0` falls outside Greenberg's hypotheses, since
$`\Qp^\vee = \Qp(1)` forces $`r_{\Qp^\vee} = 1`; but the two statements are
equivalent. More general — even non-commutative — formulations exist in the work
of Kato and of Fukaya–Kato.
:::
