import Verso
import VersoManual
import VersoBlueprint
import PadicLFunctions
import PadicLFunctionsBlueprint.Refs
import PadicLFunctionsBlueprint.TexPrelude

open Verso.Genre
open Verso.Genre.Manual
open Informal


#doc (Manual) "Iwasawa theory for modular forms" =>

The Kubota–Leopoldt picture of Parts I and II is the Iwasawa theory of
$`\GL(1)`: Dirichlet characters are the algebraic automorphic forms for
$`\GL(1)`, and $`\zeta_p` is their $`p`-adic $`L`-function. The next case is
$`\GL(2)`, whose automorphic forms are *modular forms*. Remarkably, *all* of the
$`\GL(1)` theory has a $`\GL(2)` analogue for sufficiently nice modular forms,
although the picture is not yet complete in full generality. This chapter
records the three constructions and the comparison theorems that bind them.

# Recapping the GL(1) picture

Throughout, $`p` is a fixed prime. Write
$`\Gamma^+ := \Gal(\Q(\mu_{p^\infty})^+/\Q) \cong \Zpx/\{\pm 1\}` for the Galois
group of the maximal real subfield of the cyclotomic tower, $`\Lam(\Gamma^+)`
for its Iwasawa algebra, and $`Q(\Gamma^+)` for the ring of fractions of
$`\Lam(\Gamma^+)`. The notes give three constructions of the Kubota–Leopoldt
$`p`-adic $`L`-function, and the comparison theorems are exactly what is being
generalised to $`\GL(2)`.

:::definition "mf-gl1-recap"
The three $`\GL(1)` $`p`-adic $`L`-functions are:

- *Analytic.* A $`p`-adic pseudo-measure
  $`\zeta_p^{\mathrm{an}} \in Q(\Gamma^+)` interpolating special values of the
  Riemann zeta function, built in Part I.
- *Arithmetic.* The element
  $`\zeta_p^{\mathrm{arith}} := \Col(c_\infty)`, the image under the Coleman map
  $`\Col` of the norm-coherent family of cyclotomic units $`c_\infty`.
- *Algebraic.* The characteristic ideal
  $`\zeta_p^{\mathrm{alg}} := \Char_{\Lam(\Gamma^+)}(\sX_\infty^+)
  \subset \Lam(\Gamma^+)` of the torsion $`\Lam(\Gamma^+)`-module
  $`\sX_\infty^+` (an unramified Iwasawa module).

This recapitulates {uses "kubota-leopoldt"}[] and the
{uses "pseudo-measure"}[] of Part I, the {uses "coleman-map"}[] applied to the
{uses "cyclotomic-units"}[], and the {uses "characteristic-ideal"}[] of the
Main Conjecture chapter.
:::

:::theorem "mf-gl1-comparisons"
The $`\GL(1)` comparison statements read:

- (Coleman-map computation) $`\zeta_p^{\mathrm{an}} = \zeta_p^{\mathrm{arith}}`,
  identifying the analytic and arithmetic constructions.
- (Iwasawa Main Conjecture)
  $`\zeta_p^{\mathrm{alg}} = I(\Gamma^+)\,\zeta_p^{\mathrm{an}}`, where
  $`I(\Gamma^+)` is the augmentation ideal, identifying the algebraic and
  analytic constructions.

These rest on {uses "mf-gl1-recap"}[], {uses "coleman-theorem"}[],
{uses "coleman-map"}[], {uses "cyclotomic-units"}[],
{uses "iwasawa-main-conjecture"}[] and {uses "characteristic-ideal"}[].
:::

:::proof "mf-gl1-comparisons"
The first equality is the content of the Coleman-map computation of Part II: the
Coleman map sends the cyclotomic units, whose Mellin transform recovers the
Kubota–Leopoldt interpolation property, to the analytic pseudo-measure, so the
arithmetic object equals the analytic one on the nose. The second equality is
the Iwasawa Main Conjecture, equating the characteristic ideal of $`\sX_\infty^+`
with the ideal generated by $`\zeta_p^{\mathrm{an}}` (up to the augmentation
ideal accounting for the pseudo-measure versus measure normalisation). Both are
recorded in detail in the preceding chapters; here they serve as the templates
for the $`\GL(2)` analogues.
:::

# The GL(2) setting

Fix a normalised cuspidal Hecke eigenform $`f` of weight $`k+2` and level
$`\Gamma_0(N)` with $`p \mid N`, and let $`L(f,s)` be its complex
$`L`-function. There are again three ways to attach a $`p`-adic $`L`-function to
$`f`: analytic, arithmetic and algebraic. We treat each in turn, and then state
the comparison theorems and the Main Conjecture for $`f`.

:::definition "mf-critical-values"
A complex argument $`s = j` is *critical* for $`L(f,s)` in the sense of
Deligne: $`j` is critical for a motivic $`L`-function $`L(M,s)` when neither the
Euler factor at infinity $`L_\infty(M,s)` nor $`L_\infty(M,1-s)` has a pole at
$`j`. For the eigenform $`f` this criterion singles out the values
$`L(f,\chi,j+1)` for $`\chi` an arbitrary Dirichlet character and
$`0 \le j \le k`. (For $`\GL(1)`, the same criterion recovers the negative odd
integers and positive even integers as the critical values of $`\zeta(s)`,
matching the Kubota–Leopoldt interpolation range.)
:::

# The analytic p-adic L-function

The analytic $`p`-adic $`L`-function $`L_p^{\mathrm{an}}(f)` is a $`p`-adic
distribution on $`\Zpx` that interpolates the critical values of
$`L(f,s)`. Its existence is governed by the slope $`v_p(\alpha_p)` of the
$`U_p`-eigenvalue $`\alpha_p` of $`f`.

:::theorem "mf-analytic-Lp"
Let $`\alpha_p` be the $`U_p`-eigenvalue of $`f`, and suppose
$`v_p(\alpha_p) < k+1`. Then there is a unique locally analytic distribution
$`L_p^{\mathrm{an}}(f) \in \sD^{\mathrm{la}}(\Zpx)` on $`\Zpx` such that:

- $`L_p^{\mathrm{an}}(f)` has growth of order $`v_p(\alpha_p)`; and
- for every Dirichlet character $`\chi` of conductor $`p^n` and every
  $`0 \le j \le k`,
  $$`L_p^{\mathrm{an}}(f,\overline{\chi},j+1)
    = \int_{\Zpx} \chi(x)\,x^j \cdot L_p^{\mathrm{an}}(f)
    = -\alpha_p^{-n}\left(1 - \chi(p)\tfrac{p^j}{\alpha_p}\right)
      \frac{G(\chi)\,j!\,p^{nj}}{(2\pi i)^{j+1}}
      \cdot \frac{L(f,\overline{\chi},j+1)}{\Omega_f^{\pm}},`
  where $`G(\chi)` is the Gauss sum and $`\Omega_f^{\pm}` the canonical
  complex periods.

This generalises {uses "interpolation-property"}[] and lives in the space of
{uses "locally-analytic-distribution"}[]; it depends on {uses "mf-critical-values"}[].
:::

:::proof "mf-analytic-Lp"
This is the theorem of Mazur–Swinnerton-Dyer, Amice–Vélu and Višik. One forms
the modular symbol attached to $`f`, an $`H`-valued additive functional on
$`\Q`-paths in the upper half-plane whose values along $`\{i\infty \to a/p^n\}`
encode the twisted $`L`-values $`L(f,\overline{\chi},j+1)`. Applying the
$`U_p`-operator and dividing by $`\alpha_p` makes these symbols compatible under
the maps in the cyclotomic tower; the slope bound $`v_p(\alpha_p) < k+1`
guarantees that the resulting compatible system has bounded growth of order
$`v_p(\alpha_p)`, so it defines an admissible (locally analytic) distribution on
$`\Zpx` rather than merely a sequence of values. Uniqueness follows because a
distribution of growth $`< k+1` is determined by its values against the
characters $`x \mapsto \chi(x)x^j` with $`0 \le j \le k`, which are exactly the
prescribed critical $`L`-values. The Euler factor
$`1 - \chi(p)p^j/\alpha_p` and the power $`\alpha_p^{-n}` arise from the
$`U_p`-stabilisation, exactly as the factor $`1-p^{-s}` arose for $`\zeta_p`.
:::

:::proposition "mf-ordinary-measure"
If $`f` is $`p`-*ordinary*, i.e. $`v_p(\alpha_p) = 0`, then the growth condition
forces $`L_p^{\mathrm{an}}(f)` to lie in the subspace of $`p`-adic measures on
$`\Zpx`, that is in the Iwasawa algebra $`\Lam(\Zpx) \subset \sD(\Zpx)`. This
uses {uses "mf-analytic-Lp"}[] and {uses "iwasawa-algebra"}[].
:::

:::proof "mf-ordinary-measure"
Growth of order $`0` is precisely boundedness, and a bounded locally analytic
distribution is a measure; this is the same dichotomy seen for $`\zeta_p`, where
$`p`-ordinarity (here $`v_p(\alpha_p) = 0`) places the distribution in the
Iwasawa algebra rather than the larger distribution space. The measure then
sits in $`\Lam(\Zpx)` under the Mahler/Mellin identification of measures with
the Iwasawa algebra.
:::

*Boundary and infinite slope.* If $`\alpha_p \neq 0` then
$`v_p(\alpha_p) \le k+1`, but the theorem above excludes the boundary case
$`v_p(\alpha_p) = k+1`; this is handled by the overconvergent modular-symbol
methods of Pollack–Stevens and Bellaïche, with a slightly modified statement. The
*infinite slope* case $`\alpha_p = 0` is harder still: partial $`p`-adic
$`L`-functions with good interpolation are constructed from Kato's Euler system
via Perrin-Riou's big logarithm maps. We do not develop these refinements here.

# The arithmetic p-adic L-function

The arithmetic construction generalises the Coleman-map route of Part II,
passing through the Galois representation of $`f`, Kato's Euler system and the
Perrin-Riou big logarithm map.

:::definition "mf-galois-rep"
Attached to $`f` is a two-dimensional $`p`-adic Galois representation $`V_f`,
realised by Deligne inside the étale cohomology of the modular curve. It
contains a Galois-stable integral lattice $`T_f`. The localisation of the
relevant cohomology at $`p` carries an Iwasawa cohomology group
$`\HIw(\Qp, V_f)`, the $`\GL(2)` analogue of the module of norm-coherent local
units.
:::

:::theorem "mf-kato-euler-system"
*(Kato.)* There exists an Euler system $`\mathbf{z}_{\mathrm{Kato}}(f)` attached
to the lattice $`T_f`. Localising at $`p` yields a canonical class
$$`\mathbf{z}_{\mathrm{Kato}}(f) \in \HIw(\Qp, V_f).`
This depends on {uses "mf-galois-rep"}[] and is the $`\GL(2)` analogue of
{uses "cyclotomic-units"}[].
:::

:::proof "mf-kato-euler-system"
This is the first main theorem of Kato's *Hodge–Tate, p-adic and zeta* paper.
The classes are constructed from cup products of Siegel units (modular units on
the modular curve) via the Beilinson–Kato map, producing for each integer $`m`
a class in the motivic, hence étale, cohomology $`\Hone(\Q(\mu_m), T_f(2))`. The
norm-compatibility of Siegel units along the cyclotomic tower endows the family
with the Euler-system distribution relations — exactly the role played by the
norm-coherence of cyclotomic units in the $`\GL(1)` Coleman-map construction.
Localising at $`p` and passing to the inverse limit over the tower yields the
single Iwasawa-cohomology class $`\mathbf{z}_{\mathrm{Kato}}(f)`.
:::

:::definition "mf-arithmetic-Lp"
The Perrin-Riou big logarithm map is a $`\Lam`-morphism
$$`\Log_{V_f} : \HIw(\Qp, V_f) \longrightarrow \sD^{\mathrm{la}}(\Zpx),`
the $`\GL(2)` analogue of the Coleman map. The *arithmetic $`p`-adic
$`L`-function* of $`f` is the image of Kato's class,
$$`L_p^{\mathrm{arith}}(f) := \Log_{V_f}\bigl(\mathbf{z}_{\mathrm{Kato}}(f)\bigr)
  \in \sD^{\mathrm{la}}(\Zpx).`
This uses {uses "mf-kato-euler-system"}[] and {uses "coleman-map"}[].
:::

:::theorem "mf-explicit-reciprocity"
*(Kato's explicit reciprocity law.)* The analytic and arithmetic $`p`-adic
$`L`-functions agree:
$$`L_p^{\mathrm{an}}(f) = L_p^{\mathrm{arith}}(f) \in \sD^{\mathrm{la}}(\Zpx).`
This is the $`\GL(2)` analogue of {uses "mf-gl1-comparisons"}[], and depends on
{uses "mf-analytic-Lp"}[] and {uses "mf-arithmetic-Lp"}[].
:::

:::proof "mf-explicit-reciprocity"
This is the second main theorem of Kato. The Perrin-Riou logarithm map is
characterised by an interpolation property: pairing $`\Log_{V_f}` of a class
against the de Rham data of $`V_f` recovers the dual exponential (or Bloch–Kato
exponential) of the class twisted by characters $`\chi(x)x^j`. Kato computes
these dual exponentials for his Siegel-unit classes explicitly and shows they
reproduce the same critical $`L`-values $`L(f,\overline{\chi},j+1)`, with the
identical Euler and Gauss-sum factors, that characterise
$`L_p^{\mathrm{an}}(f)`. Since both distributions have growth $`v_p(\alpha_p)`
and agree on the determining set of characters $`x \mapsto \chi(x)x^j`, they are
equal. This is precisely the $`\GL(2)` incarnation of the equality
$`\zeta_p^{\mathrm{an}} = \zeta_p^{\mathrm{arith}}` from $`\GL(1)`.
:::

# The algebraic p-adic L-function and the Main Conjecture

For a $`p`-ordinary eigenform the analytic/arithmetic $`p`-adic $`L`-function is
a measure, and we can ask for its algebraic counterpart: a characteristic ideal
of a Selmer-type Iwasawa module, exactly as in the $`\GL(1)` Main Conjecture.

:::definition "mf-algebraic-Lp"
Suppose $`f` is $`p`-ordinary ($`v_p(\alpha_p)=0`), so $`V_f` is an ordinary
Galois representation. As in the Greenberg–Selmer formalism this yields a Selmer
group, an Iwasawa module $`\sX_{p^\infty}(V_f)` over the Iwasawa algebra
$`\Lam(\Gamma)` of $`\Gamma := \Gal(\Q(\mu_{p^\infty})/\Q) \cong \Zpx`. Kato
proved this module is $`\Lam`-torsion, so it has a characteristic ideal, and the
*algebraic $`p`-adic $`L`-function of $`f`* is
$$`L_p^{\mathrm{alg}}(f) := \ch_{\Lam(\Zpx)}\bigl(\sX_{p^\infty}(V_f)\bigr).`
This is the $`\GL(2)` analogue of $`\zeta_p^{\mathrm{alg}}`; it uses
{uses "mf-galois-rep"}[], {uses "characteristic-ideal"}[] and
{uses "lambda-module-structure"}[].
:::

:::proof "mf-algebraic-Lp"
That $`\sX_{p^\infty}(V_f)` is $`\Lam`-torsion is a consequence of Kato's Euler
system: a non-trivial Euler system bounds the Selmer group, forcing it to be
torsion over $`\Lam`. A finitely generated torsion $`\Lam`-module has a
well-defined characteristic ideal by the structure theory of $`\Lam`-modules,
and $`L_p^{\mathrm{alg}}(f)` is by definition this ideal. The construction
mirrors $`\zeta_p^{\mathrm{alg}} = \Char(\sX_\infty^+)` from the $`\GL(1)` case,
with $`\sX_\infty^+` replaced by the Selmer module of $`V_f`.
:::

:::theorem "gl2-iwasawa"
*(Iwasawa Main Conjecture for $`f`.)* Let $`f` be a $`p`-ordinary cuspidal
Hecke eigenform. Under mild technical hypotheses, the analytic/arithmetic
$`p`-adic $`L`-function is a measure in $`\Lam(\Zpx)`, and the algebraic
$`p`-adic $`L`-function equals the ideal it generates:
$$`L_p^{\mathrm{alg}}(f) = \bigl(L_p^{\mathrm{an}}(f)\bigr)
  \subset \Lam(\Zpx).`
This is the $`\GL(2)` analogue of {uses "iwasawa-main-conjecture"}[]; it depends
on {uses "mf-algebraic-Lp"}[], {uses "mf-ordinary-measure"}[],
{uses "mf-explicit-reciprocity"}[] and {uses "mf-kato-euler-system"}[].
:::

:::proof "gl2-iwasawa"
This is a theorem of Kato together with Skinner–Urban. Kato's Euler system gives
one divisibility: the existence of the bounding Euler system forces
$`L_p^{\mathrm{alg}}(f) \mid (L_p^{\mathrm{an}}(f))`, i.e. the characteristic
ideal divides the analytic $`p`-adic $`L`-function — the same mechanism by which
an Euler system yields the divisibility half of any Main Conjecture. The reverse
divisibility is supplied by Skinner–Urban, who construct congruences between
$`f` and Eisenstein series on a larger unitary (or $`\GL(2)`) group; the
Eisenstein congruence manufactures enough elements of the Selmer group to bound
it from the other side, exactly as Ribet's method underlies the $`\GL(1)` Main
Conjecture. Combining the two divisibilities gives the equality of ideals. Much
subsequent work weakens the hypotheses and treats non-ordinary $`f`.
:::

*Applications.* The cyclotomic Iwasawa theory of modular forms has deep
applications to elliptic curves and the Birch–Swinnerton-Dyer conjecture. There
is also a parallel *anticyclotomic* theory, working over an auxiliary imaginary
quadratic field, with its own striking applications to BSD. These directions lie
beyond the scope of these notes.

# Further generalisations

The three constructions and the equalities between them are expected to hold in
great generality — for a Galois representation $`V` arising from a motive $`M`
and corresponding under Langlands to an automorphic representation $`\pi` — but
very few cases are complete. We record the shape of the general expectation.

:::definition "mf-general-program"
For a motivic Galois representation $`V` with automorphic avatar $`\pi`, the
three-fold program reads:

- *Analytic.* There should exist a locally analytic $`p`-adic distribution
  $`L_p^{\mathrm{an}}(V)` interpolating the critical values of $`L(V,s)`,
  subject to the precise conjectures of Coates–Perrin-Riou and Panchishkin.
- *Arithmetic.* There should exist an Euler system for $`V`; applying a
  Perrin-Riou logarithm map extracts an arithmetic $`p`-adic $`L`-function, and
  an explicit reciprocity law should give
  $`L_p^{\mathrm{an}}(V) = L_p^{\mathrm{arith}}(V)`.
- *Algebraic.* There should be an Iwasawa Main Conjecture
  $`L_p^{\mathrm{alg}}(V) = (L_p^{\mathrm{an}}(V))`, at least in ordinary
  settings.

This frames {uses "gl2-iwasawa"}[] and {uses "mf-explicit-reciprocity"}[] as the
$`\GL(2)` instance.
:::

*State of the art.* The known cases are fragmentary. On the analytic side,
$`\GL(1)` and $`\GL(2)`
are as above, $`\GL(3)` was handled only recently (with the symmetric-square
case known much earlier), and no general construction is known for $`\GL(n)`
with $`n \ge 4`; there are scattered results for unitary groups, Siegel modular
forms and $`\GL_{n+1}\times\GL_n`. On the arithmetic side, Euler systems remain
rare — Kato's system, cyclotomic units and elliptic units were long almost the
only examples — though the last decade has seen new constructions (Rankin–Selberg
products, diagonal cycles for triple products, and $`\mathrm{GSp}_4`), each
demanding its own explicit reciprocity law. On the algebraic side, Main
Conjectures are known in wide ordinary generality, and an Euler system together
with $`L_p^{\mathrm{an}} = L_p^{\mathrm{arith}}` always yields torsionness of the
Selmer group and the divisibility $`L_p^{\mathrm{alg}} \mid (L_p^{\mathrm{an}})`.
