/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import PadicLFunctions.Iwasawa.LocalUnits
import PadicLFunctions.Coleman.Map

/-!
# Cyclotomic units: the global modules 𝒟_n and their local closures 𝒞 (RJW §11.3)

RJW (arXiv:2309.15692) §11.3 (TeX 3060–3112) + the §9 global notation (TeX
2471–2475). All objects live inside `ℂ_[p]` (decomposition replan R11.7):

* the global fields `F_n = ℚ(μ_{p^n})` and `F_n⁺` as `IntermediateField ℚ ℂ_[p]`;
* the global units `𝒱_n = 𝒪_{F_n}^×` (units integral over `ℤ` with integral
  inverse), with `𝒱_n ≤ 𝒰_n` via `‖x‖ ≤ 1` for `ℤ`-integral `x`;
* **the cyclotomic units** `𝒟_n` = (subgroup generated by `±ξ_{p^n}` and the
  `ξ_{p^n}^a − 1`) ∩ `𝒱_n`, and `𝒟_n⁺` (RJW Definition, TeX 3065–3067);
* the local closures `𝒞_n` (p-adic closure of `𝒟_n` in `𝒰_n`), `𝒞_{n,1}`,
  and the towers `𝒞_{∞,1}`, `𝒞⁺_{∞,1}` (RJW Definition, TeX 3090–3094);
* **the milestone** (RJW TeX 3084): the Coleman-map inputs `c_n(a)` "are naturally
  elements of `𝒟_n`, hence global" — `cyclo ∈ 𝒞_{∞,1} ≤ 𝒰_{∞,1}`.

NOT here (recorded deferrals): the class-number index theorem
`h_n⁺ = [𝒱_n : 𝒟_n]` (TeX 3072 — the notes cite Washington Thm 8.2 without proof;
permanently deferred prose) and `thm:iwasawa` itself (TeX 3098 — statement and proof
on the §12 board, where its Λ(𝒢⁺)-module structures are constructed).
-/

open scoped IntermediateField

namespace PadicLFunctions

namespace Coleman

variable (p : ℕ) [hp : Fact p.Prime]

/-! ## The global tower F_n, F_n⁺ and the global units 𝒱_n (RJW TeX 2471–2472) -/

/-- `F_n = ℚ(μ_{p^n})`, inside `ℂ_[p]` (RJW TeX 2471). -/
noncomputable def Fglobal (n : ℕ) : IntermediateField ℚ ℂ_[p] :=
  ℚ⟮zetaSys p n⟯

/-- `F_n⁺ = ℚ(ξ_{p^n} + ξ_{p^n}⁻¹)`: the maximal totally real subfield, rendered by
its standard concrete generator (RJW TeX 2471/2475). -/
noncomputable def FglobalPlus (n : ℕ) : IntermediateField ℚ ℂ_[p] :=
  ℚ⟮zetaSys p n + (zetaSys p n)⁻¹⟯

lemma FglobalPlus_le_Fglobal (n : ℕ) : FglobalPlus p n ≤ Fglobal p n := by
  rw [FglobalPlus, IntermediateField.adjoin_simple_le_iff]
  exact add_mem (IntermediateField.mem_adjoin_simple_self ℚ _)
    ((Fglobal p n).inv_mem (IntermediateField.mem_adjoin_simple_self ℚ _))

/-- Elements integral over `ℤ` have norm at most `1` in `ℂ_[p]` (the ultrametric
estimate on a monic integral relation; replan R11.7 — the direct route, no spectral
theory). -/
theorem norm_le_one_of_isIntegral_int {x : ℂ_[p]} (hx : IsIntegral ℤ x) :
    ‖x‖ ≤ 1 := by
  obtain ⟨P, hPmonic, hPx⟩ := hx
  by_contra h1
  push Not at h1
  set N : ℕ := P.natDegree with hNdef
  -- the integral relation, written as `x^N = −Σ_{i<N} aᵢ x^i`
  have hsum : ∑ i ∈ Finset.range (N + 1),
      (algebraMap ℤ ℂ_[p]) (P.coeff i) * x ^ i = 0 := by
    rw [← Polynomial.eval₂_eq_sum_range]; exact hPx
  have htop : x ^ N
      = -∑ i ∈ Finset.range N, (algebraMap ℤ ℂ_[p]) (P.coeff i) * x ^ i := by
    rw [Finset.sum_range_succ] at hsum
    have hlead : (algebraMap ℤ ℂ_[p]) (P.coeff N) * x ^ N = x ^ N := by
      rw [hNdef, hPmonic.coeff_natDegree, map_one, one_mul]
    rw [hlead, add_comm, ← eq_neg_iff_add_eq_zero] at hsum
    exact hsum
  -- each lower term has norm `≤ ‖x‖^(N−1) < ‖x‖^N` (integer coefficients, smaller power)
  have hxpos : (0 : ℝ) < ‖x‖ := lt_trans one_pos h1
  rcases Nat.eq_zero_or_pos N with hN0 | hNpos
  · -- `N = 0`: the relation reads `1 = 0`
    rw [hN0, Finset.range_zero, Finset.sum_empty, neg_zero, pow_zero] at htop
    exact absurd htop one_ne_zero
  -- `N ≥ 1`: the ultrametric bound dominates the sum by one of its terms `< ‖x‖^N`
  obtain ⟨i, hi, hile⟩ := IsUltrametricDist.exists_norm_finsetSum_le_of_nonempty
    (t := Finset.range N) ⟨0, Finset.mem_range.2 hNpos⟩
    (fun i => (algebraMap ℤ ℂ_[p]) (P.coeff i) * x ^ i)
  have hilt : i < N := Finset.mem_range.1 hi
  have hcoeff : ‖(algebraMap ℤ ℂ_[p]) (P.coeff i)‖ ≤ 1 := by
    rw [show (algebraMap ℤ ℂ_[p]) (P.coeff i) = ((P.coeff i : ℤ) : ℂ_[p]) by
      simp [algebraMap_int_eq]]
    exact IsUltrametricDist.norm_intCast_le_one ℂ_[p] _
  have hterm : ‖(algebraMap ℤ ℂ_[p]) (P.coeff i) * x ^ i‖ ≤ ‖x‖ ^ (N - 1) := by
    rw [norm_mul, norm_pow]
    calc ‖(algebraMap ℤ ℂ_[p]) (P.coeff i)‖ * ‖x‖ ^ i
        ≤ 1 * ‖x‖ ^ i := by
          exact mul_le_mul_of_nonneg_right hcoeff (by positivity)
      _ = ‖x‖ ^ i := one_mul _
      _ ≤ ‖x‖ ^ (N - 1) := pow_le_pow_right₀ h1.le (by omega)
  have hxNbound : ‖x‖ ^ N ≤ ‖x‖ ^ (N - 1) := by
    calc ‖x‖ ^ N = ‖x ^ N‖ := (norm_pow x N).symm
      _ = ‖∑ i ∈ Finset.range N, (algebraMap ℤ ℂ_[p]) (P.coeff i) * x ^ i‖ := by
          rw [htop, norm_neg]
      _ ≤ ‖(algebraMap ℤ ℂ_[p]) (P.coeff i) * x ^ i‖ := hile
      _ ≤ ‖x‖ ^ (N - 1) := hterm
  have hlt : ‖x‖ ^ (N - 1) < ‖x‖ ^ N :=
    pow_lt_pow_right₀ h1 (by omega)
  exact absurd (lt_of_le_of_lt hxNbound hlt) (lt_irrefl _)

/-- `𝒱_n = 𝒪_{F_n}^×`: the global units — units of `ℂ_[p]` lying in `F_n`,
integral over `ℤ` together with their inverses (RJW TeX 2472). -/
noncomputable def globalUnits (n : ℕ) : Subgroup ℂ_[p]ˣ where
  carrier := {u | (u : ℂ_[p]) ∈ Fglobal p n ∧ IsIntegral ℤ (u : ℂ_[p])
    ∧ IsIntegral ℤ ((u⁻¹ : ℂ_[p]ˣ) : ℂ_[p])}
  mul_mem' {u v} hu hv := by
    refine ⟨?_, ?_, ?_⟩
    · rw [Units.val_mul]; exact mul_mem hu.1 hv.1
    · rw [Units.val_mul]; exact hu.2.1.mul hv.2.1
    · rw [mul_inv_rev, Units.val_mul]; exact hv.2.2.mul hu.2.2
  one_mem' := by
    refine ⟨?_, ?_, ?_⟩
    · rw [Units.val_one]; exact one_mem _
    · rw [Units.val_one]; exact isIntegral_one
    · rw [inv_one, Units.val_one]; exact isIntegral_one
  inv_mem' {u} hu := by
    refine ⟨?_, hu.2.2, ?_⟩
    · rw [Units.val_inv_eq_inv_val]; exact (Fglobal p n).inv_mem hu.1
    · rw [inv_inv]; exact hu.2.1

/-- `𝒱_n⁺ = 𝒪_{F_n⁺}^×` (RJW TeX 2472). -/
noncomputable def globalUnitsPlus (n : ℕ) : Subgroup ℂ_[p]ˣ where
  carrier := {u | u ∈ globalUnits p n ∧ (u : ℂ_[p]) ∈ FglobalPlus p n}
  mul_mem' {u v} hu hv := by
    refine ⟨mul_mem hu.1 hv.1, ?_⟩
    rw [Units.val_mul]
    exact mul_mem hu.2 hv.2
  one_mem' := by
    refine ⟨one_mem _, ?_⟩
    rw [Units.val_one]
    exact one_mem _
  inv_mem' {u} hu := by
    refine ⟨(globalUnits p n).inv_mem hu.1, ?_⟩
    rw [Units.val_inv_eq_inv_val]
    exact (FglobalPlus p n).inv_mem hu.2

/-- `F_n = ℚ(ξ_{p^n}) ⊆ K_n = ℚ_p(ξ_{p^n})` at the level of `ℂ_[p]`-subsets: every
element of the rational cyclotomic field lies in the local cyclotomic field
(both are adjoined the same generator `ξ_{p^n}`, and `K_n` contains `ℚ_p ⊇ ℚ`). -/
lemma Fglobal_le_K {n : ℕ} {x : ℂ_[p]} (hx : x ∈ Fglobal p n) : x ∈ K p n := by
  rw [Fglobal] at hx
  induction hx using IntermediateField.adjoin_induction with
  | mem y hy => obtain rfl := hy; exact zetaSys_mem_K p n
  | algebraMap q =>
      rw [eq_ratCast (algebraMap ℚ ℂ_[p]) q]
      exact SubfieldClass.ratCast_mem (K p n) q
  | add y z _ _ hy hz => exact add_mem hy hz
  | inv y _ hy => exact (K p n).inv_mem hy
  | mul y z _ _ hy hz => exact mul_mem hy hz

/-- Global units are local units: `𝒱_n ≤ 𝒰_n` (`ℤ`-integral elements land in the
unit ball, so a global unit and its inverse lie in `O_n`). The "image inside the
space of local units" of RJW TeX 3084. -/
theorem globalUnits_le_localUnits (n : ℕ) : globalUnits p n ≤ localUnits p n := by
  intro u hu
  rw [mem_localUnits_iff]
  obtain ⟨hF, hint, hintinv⟩ := hu
  refine ⟨?_, ?_⟩
  · rw [O, Subring.mem_inf]
    exact ⟨Fglobal_le_K p hF, norm_le_one_of_isIntegral_int p hint⟩
  · rw [O, Subring.mem_inf]
    refine ⟨Fglobal_le_K p ?_, norm_le_one_of_isIntegral_int p hintinv⟩
    rw [Units.val_inv_eq_inv_val]
    exact (Fglobal p n).inv_mem hF

/-! ## The cyclotomic units 𝒟_n (RJW Definition, TeX 3065–3067) -/

/-- The generating set `{±ξ_{p^n}} ∪ {ξ_{p^n}^a − 1 : 1 ≤ a ≤ p^n − 1}` of RJW
TeX 3066, as a set of units of `ℂ_[p]` (each generator is a nonzero element of
`F_n^×`; specified through `Units.val` to avoid choices of `Units.mk0`-proofs). -/
def cycloGenSet (n : ℕ) : Set ℂ_[p]ˣ :=
  {u | (u : ℂ_[p]) = zetaSys p n ∨ (u : ℂ_[p]) = -(zetaSys p n)
    ∨ ∃ a : ℕ, 1 ≤ a ∧ a ≤ p ^ n - 1 ∧ (u : ℂ_[p]) = zetaSys p n ^ a - 1}

/-- **RJW Definition (TeX 3065–3067)**: the group `𝒟_n` of cyclotomic units of
`F_n` — the intersection of `𝒪_{F_n}^×` with the multiplicative subgroup of `F_n^×`
generated by `±ξ_{p^n}` and the `ξ_{p^n}^a − 1` (the generators all lie in `F_n`,
so closing inside `ℂ_[p]ˣ` is the same as closing inside `F_n^×`). -/
noncomputable def cycloUnits (n : ℕ) : Subgroup ℂ_[p]ˣ :=
  Subgroup.closure (cycloGenSet p n) ⊓ globalUnits p n

/-- `𝒟_n⁺ = 𝒟_n ∩ F_n⁺` (RJW TeX 3066). -/
noncomputable def cycloUnitsPlus (n : ℕ) : Subgroup ℂ_[p]ˣ where
  carrier := {u | u ∈ cycloUnits p n ∧ (u : ℂ_[p]) ∈ FglobalPlus p n}
  mul_mem' {u v} hu hv := by
    refine ⟨mul_mem hu.1 hv.1, ?_⟩
    rw [Units.val_mul]
    exact mul_mem hu.2 hv.2
  one_mem' := by
    refine ⟨one_mem _, ?_⟩
    rw [Units.val_one]
    exact one_mem _
  inv_mem' {u} hu := by
    refine ⟨(cycloUnits p n).inv_mem hu.1, ?_⟩
    rw [Units.val_inv_eq_inv_val]
    exact (FglobalPlus p n).inv_mem hu.2

lemma cycloUnits_le_globalUnits (n : ℕ) : cycloUnits p n ≤ globalUnits p n :=
  inf_le_right

/-! ## The local closures 𝒞 (RJW Definition, TeX 3090–3094) -/

/-- **RJW Definition (TeX 3090)**: `𝒞_n` — the p-adic closure of `𝒟_n` inside the
local units `𝒰_n` (topological closure in the topological group `ℂ_[p]ˣ`,
intersected into `𝒰_n`; since `𝒟_n ≤ 𝒰_n` and `𝒰_n` is closed, this is the honest
subspace closure — the explicit description is `lem:closure`, §12). -/
noncomputable def cycloClosure (n : ℕ) : Subgroup ℂ_[p]ˣ :=
  (cycloUnits p n).topologicalClosure ⊓ localUnits p n

/-- `𝒞_n⁺ = 𝒞_n ∩ 𝒰_n⁺` (RJW TeX 3090). -/
noncomputable def cycloClosurePlus (n : ℕ) : Subgroup ℂ_[p]ˣ :=
  cycloClosure p n ⊓ localUnitsPlus p n

/-- `𝒞_{n,1} = 𝒞_n ∩ 𝒰_{n,1}` (RJW TeX 3091). -/
noncomputable def cycloClosureOne (n : ℕ) : Subgroup ℂ_[p]ˣ :=
  cycloClosure p n ⊓ localUnitsOne p n

/-- `𝒞⁺_{n,1} = 𝒞_n⁺ ∩ 𝒰_{n,1}` (RJW TeX 3091). -/
noncomputable def cycloClosureOnePlus (n : ℕ) : Subgroup ℂ_[p]ˣ :=
  cycloClosurePlus p n ⊓ localUnitsOne p n

/-- `𝒞_{∞,1} = lim←_{n≥1} 𝒞_{n,1}` (RJW TeX 3092), as a subgroup of `𝒰_∞`. -/
noncomputable def cycloTower1 : Subgroup (NormCompatUnits p) where
  carrier := {u | ∀ n, 1 ≤ n → u.elems n ∈ cycloClosureOne p n}
  mul_mem' hu hv n hn := mul_mem (hu n hn) (hv n hn)
  one_mem' _ _ := one_mem _
  inv_mem' hu n hn := (cycloClosureOne p n).inv_mem (hu n hn)

/-- `𝒞⁺_{∞,1} = lim←_{n≥1} 𝒞⁺_{n,1}` (RJW TeX 3092). -/
noncomputable def cycloTower1Plus : Subgroup (NormCompatUnits p) where
  carrier := {u | ∀ n, 1 ≤ n → u.elems n ∈ cycloClosureOnePlus p n}
  mul_mem' hu hv n hn := mul_mem (hu n hn) (hv n hn)
  one_mem' _ _ := one_mem _
  inv_mem' hu n hn := (cycloClosureOnePlus p n).inv_mem (hu n hn)

lemma cycloTower1_le_unitsTower1 : cycloTower1 p ≤ unitsTower1 p :=
  fun _ hu n hn => (Subgroup.mem_inf.1 (hu n hn)).2

/-! ## The milestone: the Coleman inputs are global cyclotomic units (RJW TeX 3084)

"The cyclotomic units `c_n(a)`, introduced in §10.2, are naturally elements of
`𝒟_n`, hence global." -/

/-- `ξ_{p^n}` is integral over `ℤ` (a primitive `p^n`-th root of unity, hence a root
of unity, hence integral). -/
private theorem zetaSys_isIntegral (n : ℕ) : IsIntegral ℤ (zetaSys p n) :=
  (zetaSys_primitiveRoot p n).isIntegral (pow_pos hp.out.pos n)

/-- `c_n(a) = (ξ^a−1)/(ξ−1) = Σ_{i<a} ξ^i`: the cyclotomic unit is the geometric sum.
Clear the denominator (`ξ−1 ≠ 0` for `n ≥ 1`) and apply `geom_sum_mul`. -/
private theorem cycloUnit_eq_geomSum {a : ℕ} {n : ℕ} (hn : 1 ≤ n) :
    cycloUnit p a n = ∑ i ∈ Finset.range a, zetaSys p n ^ i := by
  have hne : zetaSys p n - 1 ≠ 0 :=
    sub_ne_zero_of_ne ((zetaSys_primitiveRoot p n).ne_one (one_lt_pow₀ hp.out.one_lt (by omega)))
  rw [cycloUnit, div_eq_iff hne, geom_sum_mul]

/-- `c_n(a) = 1 + ξ + ⋯ + ξ^{a−1}` is integral over `ℤ` (a `ℤ`-polynomial in the
`ℤ`-integral `ξ`). -/
theorem isIntegral_cycloUnit {a : ℕ} (_ha : ¬ (p : ℕ) ∣ a) {n : ℕ} (hn : 1 ≤ n) :
    IsIntegral ℤ (cycloUnit p a n) := by
  rw [cycloUnit_eq_geomSum p hn]
  exact IsIntegral.sum _ fun i _ => (zetaSys_isIntegral p n).pow i

/-- `orderOf ξ_{p^n} = p^n` (the primitive-root order). -/
private theorem orderOf_zetaSys (n : ℕ) : orderOf (zetaSys p n) = p ^ n :=
  ((zetaSys_primitiveRoot p n).eq_orderOf).symm

/-- The inverse `c_n(a)⁻¹ = (ξ−1)/(ξ^a−1) = Σ_{i<a'} (ξ^a)^i` for `a·a' ≡ 1 mod p^n`:
pick `a'` (`exists_mul_mod_eq_one_of_coprime`), reduce `ξ^{a·a'} = ξ` via
`pow_mod_orderOf`, then `(ξ^a−1)·Σ_{i<a'}(ξ^a)^i = (ξ^a)^{a'}−1 = ξ−1` (`geom_sum_mul`)
forces the quotient `c_n(a)⁻¹` to be that sum. -/
private theorem inv_cycloUnit_eq_geomSum {a : ℕ} (ha : ¬ (p : ℕ) ∣ a) {n : ℕ}
    (hn : 1 ≤ n) :
    ∃ a' : ℕ, (cycloUnit p a n)⁻¹ = ∑ i ∈ Finset.range a', (zetaSys p n ^ a) ^ i := by
  -- `a` is coprime to `p^n`
  have hcop : Nat.Coprime a (p ^ n) :=
    Nat.Coprime.pow_right _ ((hp.out.coprime_iff_not_dvd).2 ha).symm
  have hpn1 : 1 < p ^ n := one_lt_pow₀ hp.out.one_lt (by omega)
  obtain ⟨a', _, haa'⟩ := Nat.exists_mul_mod_eq_one_of_coprime hcop hpn1
  refine ⟨a', ?_⟩
  -- `ξ^{a·a'} = ξ`
  have hpow : zetaSys p n ^ (a * a') = zetaSys p n := by
    rw [← pow_mod_orderOf, orderOf_zetaSys, haa', pow_one]
  -- `(ξ^a − 1)·Σ_{i<a'}(ξ^a)^i = ξ − 1`
  have hgeom : (zetaSys p n ^ a - 1) * ∑ i ∈ Finset.range a', (zetaSys p n ^ a) ^ i
      = zetaSys p n - 1 := by
    rw [mul_comm, geom_sum_mul, ← pow_mul, hpow]
  -- the denominators are nonzero
  have hden1 : zetaSys p n - 1 ≠ 0 :=
    sub_ne_zero_of_ne ((zetaSys_primitiveRoot p n).ne_one hpn1)
  have hden2 : zetaSys p n ^ a - 1 ≠ 0 := by
    intro h
    rw [h, zero_mul] at hgeom
    exact hden1 hgeom.symm
  -- `c_n(a)⁻¹ = (ξ−1)/(ξ^a−1)` equals the sum
  rw [cycloUnit, inv_div, div_eq_iff hden2, mul_comm, hgeom]

/-- The inverse `c_n(a)⁻¹ = (ξ−1)/(ξ^a−1) = 1 + ξ^a + ⋯ + ξ^{(a'−1)a}` (for
`a·a' ≡ 1 mod p^n`) is integral over `ℤ`. -/
theorem isIntegral_inv_cycloUnit {a : ℕ} (ha : ¬ (p : ℕ) ∣ a) {n : ℕ} (hn : 1 ≤ n) :
    IsIntegral ℤ (cycloUnit p a n)⁻¹ := by
  obtain ⟨a', ha'⟩ := inv_cycloUnit_eq_geomSum p ha hn
  rw [ha']
  exact IsIntegral.sum _ fun i _ => ((zetaSys_isIntegral p n).pow a).pow i

/-- The norm of a primitive `p^n`-th root of unity in `ℂ_p` is `1`. (Copied from
`Coleman/Map.lean`'s private helper for the `‖ξ^i − 1‖ < 1` estimate; dedupe at
CLEANUP-FINAL.) -/
private theorem norm_primitiveRoot_eq_one' {n : ℕ} {ξ : ℂ_[p]}
    (hξ : IsPrimitiveRoot ξ (p ^ n)) : ‖ξ‖ = 1 := by
  have h1 : ‖ξ‖ ^ (p ^ n) = 1 := by rw [← norm_pow, hξ.pow_eq_one, norm_one]
  have hne : p ^ n ≠ 0 := (pow_pos hp.out.pos n).ne'
  refine le_antisymm ?_ ?_
  · by_contra h; rw [not_le] at h; exact absurd h1 (one_lt_pow₀ h hne).ne'
  · by_contra h; rw [not_le] at h; exact absurd h1 (pow_lt_one₀ (norm_nonneg ξ) h hne).ne

/-- For a norm-one `ξ`, `‖ξ^c − 1‖ ≤ ‖ξ − 1‖`. (Copied from `Coleman/Map.lean`'s
private helper; dedupe at CLEANUP-FINAL.) -/
private theorem norm_pow_sub_one_le' {ξ : ℂ_[p]} (hξ1 : ‖ξ‖ = 1) (c : ℕ) :
    ‖ξ ^ c - 1‖ ≤ ‖ξ - 1‖ := by
  rw [show ξ ^ c - 1 = (∑ i ∈ Finset.range c, ξ ^ i) * (ξ - 1) from (geom_sum_mul ξ c).symm,
    norm_mul]
  have hgeom : ‖∑ i ∈ Finset.range c, ξ ^ i‖ ≤ 1 :=
    IsUltrametricDist.norm_sum_le_of_forall_le_of_nonneg zero_le_one
      (fun i _ => by rw [norm_pow, hξ1, one_pow])
  nlinarith [norm_nonneg (ξ - 1), hgeom]

/-- `‖ξ_{p^n}^i − 1‖ < 1` for every `i`: bound it by `‖ξ_{p^n} − 1‖ = ‖π_n‖ < 1`
(`norm_pow_sub_one_le'`, `ξ_{p^n}` has norm `1`). -/
private theorem norm_zetaSys_pow_sub_one_lt_one {n : ℕ} (hn : 1 ≤ n) (i : ℕ) :
    ‖zetaSys p n ^ i - 1‖ < 1 := by
  have h1 : ‖zetaSys p n‖ = 1 := norm_primitiveRoot_eq_one' p (zetaSys_primitiveRoot p n)
  refine lt_of_le_of_lt (norm_pow_sub_one_le' p h1 i) ?_
  have := norm_pi_lt_one p hn
  rwa [pi] at this

/-- For `a ≡ 1 (mod p)`, `‖(a : ℂ_[p]) − 1‖ < 1`: `a − 1 = p·k`, so the cast is
`(p : ℂ_[p])·(k : ℂ_[p])` of norm `≤ p⁻¹·1 < 1`. -/
private theorem norm_natCast_sub_one_lt_one_of_modEq {a : ℕ} (ha1 : a ≡ 1 [MOD p]) :
    ‖(a : ℂ_[p]) - 1‖ < 1 := by
  have hple : 1 ≤ a := by
    rcases Nat.eq_zero_or_pos a with h0 | h0
    · subst h0
      have hdvd : p ∣ 1 := Nat.modEq_zero_iff_dvd.1 ha1.symm
      exact absurd (Nat.le_of_dvd one_pos hdvd) (by simpa using hp.out.one_lt)
    · exact h0
  obtain ⟨k, hk⟩ : p ∣ a - 1 := (Nat.modEq_iff_dvd' hple).1 ha1.symm
  have hcast : (a : ℂ_[p]) - 1 = (p : ℂ_[p]) * (k : ℂ_[p]) := by
    have : ((a - 1 : ℕ) : ℂ_[p]) = (a : ℂ_[p]) - 1 := by
      rw [Nat.cast_sub hple, Nat.cast_one]
    rw [← this, hk, Nat.cast_mul]
  have hpnorm : ‖(p : ℂ_[p])‖ = (p : ℝ)⁻¹ := by
    rw [show ((p : ℂ_[p])) = algebraMap ℚ_[p] ℂ_[p] (p : ℚ_[p]) by rw [map_natCast],
      norm_algebraMap', Padic.norm_p]
  rw [hcast, norm_mul, hpnorm]
  have hk1 : ‖(k : ℂ_[p])‖ ≤ 1 := IsUltrametricDist.norm_natCast_le_one ℂ_[p] k
  have hp1 : (1 : ℝ) < p := by exact_mod_cast hp.out.one_lt
  calc (p : ℝ)⁻¹ * ‖(k : ℂ_[p])‖ ≤ (p : ℝ)⁻¹ * 1 :=
        mul_le_mul_of_nonneg_left hk1 (by positivity)
    _ = (p : ℝ)⁻¹ := mul_one _
    _ < 1 := by rw [inv_lt_one_iff₀]; right; exact hp1

/-- `c_n(a)` is `≡ 1 mod 𝔭_n` when `a ≡ 1 (mod p)`: `c_n(a) − 1 = Σ_{i<a}(ξ^i − 1)
+ (a − 1)` has norm `< 1`.

Statement note (T1113): hypothesis `a ≡ 1 (mod p)` added — for `a ≢ 1 (mod p)` the
cyclotomic unit `c_n(a) ≡ a (mod 𝔭_n)` is not a principal unit (`‖c_n(a) − 1‖ = 1`),
so membership in `𝒞_{n,1}/𝒰_{n,1}` genuinely requires it; RJW glosses this (the §12
arguments use the principal-unit part); recorded in the b2-protocol log by the
orchestrator. -/
theorem norm_cycloUnit_sub_one_lt_one {a : ℕ} (_ha : ¬ (p : ℕ) ∣ a) {n : ℕ}
    (hn : 1 ≤ n) (ha1 : a ≡ 1 [MOD p]) :
    ‖cycloUnit p a n - 1‖ < 1 := by
  -- `c_n(a) − a = Σ_{i<a}(ξ^i − 1)`
  have hca : cycloUnit p a n - (a : ℂ_[p]) = ∑ i ∈ Finset.range a, (zetaSys p n ^ i - 1) := by
    rw [cycloUnit_eq_geomSum p hn, Finset.sum_sub_distrib, Finset.sum_const,
      Finset.card_range, nsmul_eq_mul, mul_one]
  -- `‖Σ_{i<a}(ξ^i − 1)‖ ≤ ‖π_n‖ < 1`
  have hsum : ‖∑ i ∈ Finset.range a, (zetaSys p n ^ i - 1)‖ < 1 := by
    refine lt_of_le_of_lt (IsUltrametricDist.norm_sum_le_of_forall_le_of_nonneg
      (norm_nonneg (pi p n)) (fun i _ => ?_)) (norm_pi_lt_one p hn)
    have h1 : ‖zetaSys p n‖ = 1 := norm_primitiveRoot_eq_one' p (zetaSys_primitiveRoot p n)
    have := norm_pow_sub_one_le' p h1 i
    rwa [pi]
  -- `c_n(a) − 1 = (c_n(a) − a) + (a − 1)`, both norms `< 1`
  have hsplit : cycloUnit p a n - 1
      = (cycloUnit p a n - (a : ℂ_[p])) + ((a : ℂ_[p]) - 1) := by ring
  rw [hsplit]
  refine lt_of_le_of_lt (IsUltrametricDist.norm_add_le_max _ _) (max_lt ?_ ?_)
  · rw [hca]; exact hsum
  · exact norm_natCast_sub_one_lt_one_of_modEq p ha1

/-- `c_n(a) = Σ_{i<a} ξ^i ∈ F_n` (a polynomial in the generator `ξ_{p^n}` of `F_n`). -/
private theorem cycloUnit_mem_Fglobal {a : ℕ} {n : ℕ} (hn : 1 ≤ n) :
    cycloUnit p a n ∈ Fglobal p n := by
  rw [cycloUnit_eq_geomSum p hn]
  exact sum_mem fun i _ => pow_mem (IntermediateField.mem_adjoin_simple_self ℚ _) i

/-- `c_n(a)` (as a `ℂ_[p]ˣ`) lies in `𝒱_n`: it is in `F_n`, integral over `ℤ`, with
integral inverse. -/
private theorem cyclo_elems_mem_globalUnits {a : ℕ} (ha : ¬ (p : ℕ) ∣ a) (hp2 : p ≠ 2)
    {n : ℕ} (hn : 1 ≤ n) :
    (cyclo p ha hp2).elems n ∈ globalUnits p n := by
  have hval : ((cyclo p ha hp2).elems n : ℂ_[p]) = cycloUnit p a n := by
    change ((if hn : 1 ≤ n then Units.mk0 (cycloUnit p a n)
      (cycloUnit_ne_zero p ha hn) else 1 : ℂ_[p]ˣ) : ℂ_[p]) = _
    rw [dif_pos hn, Units.val_mk0]
  have hinv : ((((cyclo p ha hp2).elems n)⁻¹ : ℂ_[p]ˣ) : ℂ_[p]) = (cycloUnit p a n)⁻¹ := by
    rw [Units.val_inv_eq_inv_val, hval]
  refine ⟨?_, ?_, ?_⟩
  · rw [hval]; exact cycloUnit_mem_Fglobal p hn
  · rw [hval]; exact isIntegral_cycloUnit p ha hn
  · rw [hinv]; exact isIntegral_inv_cycloUnit p ha hn

/-- **RJW TeX 3084**: `c_n(a) ∈ 𝒟_n` — membership in the generated subgroup (the
word `(ξ^a−1)·(ξ−1)⁻¹`, with `a` reduced mod `p^n`) together with global
integrality. -/
theorem cyclo_elems_mem_cycloUnits {a : ℕ} (ha : ¬ (p : ℕ) ∣ a) (hp2 : p ≠ 2)
    {n : ℕ} (hn : 1 ≤ n) :
    (cyclo p ha hp2).elems n ∈ cycloUnits p n := by
  rw [cycloUnits, Subgroup.mem_inf]
  refine ⟨?_, cyclo_elems_mem_globalUnits p ha hp2 hn⟩
  -- the word `(ξ^{a%p^n}−1)·(ξ−1)⁻¹`
  have hpn1 : 1 < p ^ n := one_lt_pow₀ hp.out.one_lt (by omega)
  have hne1 : zetaSys p n - 1 ≠ 0 :=
    sub_ne_zero_of_ne ((zetaSys_primitiveRoot p n).ne_one hpn1)
  -- `p^n ∤ a`, so `a % p^n ≠ 0`
  have hpndvd : ¬ p ^ n ∣ a := fun h => ha (dvd_trans (dvd_pow_self p (by omega)) h)
  have hmod_pos : 1 ≤ a % p ^ n := by
    rcases Nat.eq_zero_or_pos (a % p ^ n) with h0 | h0
    · exact absurd (Nat.dvd_of_mod_eq_zero h0) hpndvd
    · exact h0
  have hmodlt0 : a % p ^ n < p ^ n := Nat.mod_lt _ (by positivity)
  have hmod_lt : a % p ^ n ≤ p ^ n - 1 := by omega
  have hne2 : zetaSys p n ^ (a % p ^ n) - 1 ≠ 0 := by
    refine sub_ne_zero_of_ne fun h => ?_
    have hord : p ^ n ∣ a % p ^ n := by
      have := orderOf_dvd_of_pow_eq_one h
      rwa [orderOf_zetaSys] at this
    exact absurd (Nat.eq_zero_of_dvd_of_lt hord hmodlt0) (by omega)
  set num : ℂ_[p]ˣ := Units.mk0 (zetaSys p n ^ (a % p ^ n) - 1) hne2 with hnumdef
  set den : ℂ_[p]ˣ := Units.mk0 (zetaSys p n - 1) hne1 with hdendef
  have hnummem : num ∈ cycloGenSet p n :=
    Or.inr (Or.inr ⟨a % p ^ n, hmod_pos, hmod_lt, by rw [hnumdef, Units.val_mk0]⟩)
  have hdenmem : den ∈ cycloGenSet p n :=
    Or.inr (Or.inr ⟨1, le_rfl, Nat.le_sub_one_of_lt hpn1,
      by rw [hdendef, Units.val_mk0, pow_one]⟩)
  have hpowred : zetaSys p n ^ a = zetaSys p n ^ (a % p ^ n) := by
    rw [← orderOf_zetaSys p n, pow_mod_orderOf]
  have hword : (cyclo p ha hp2).elems n = num * den⁻¹ := by
    refine Units.ext ?_
    change ((if hn : 1 ≤ n then Units.mk0 (cycloUnit p a n)
      (cycloUnit_ne_zero p ha hn) else 1 : ℂ_[p]ˣ) : ℂ_[p]) = _
    rw [dif_pos hn, Units.val_mk0, Units.val_mul,
      show ((den⁻¹ : ℂ_[p]ˣ) : ℂ_[p]) = (zetaSys p n - 1)⁻¹ from rfl, hnumdef, Units.val_mk0,
      cycloUnit, hpowred, div_eq_mul_inv]
  rw [hword]
  exact mul_mem (Subgroup.subset_closure hnummem)
    (Subgroup.inv_mem _ (Subgroup.subset_closure hdenmem))

/-- **MILESTONE (RJW TeX 3084 + the Definition of TeX 3090–3094)**: the
norm-compatible system of cyclotomic units — the input of the Coleman map in
`coleman_to_kl` — lives in `𝒞_{∞,1}`: the global cyclotomic units, closed up
inside the principal local units, in their norm-compatible tower.

Statement note (T1113): hypothesis `a ≡ 1 (mod p)` added — for `a ≢ 1 (mod p)` the
cyclotomic unit `c_n(a) ≡ a (mod 𝔭_n)` is not a principal unit, so membership in
`𝒞_{n,1}` (`= 𝒞_n ∩ 𝒰_{n,1}`) genuinely requires it; RJW glosses this (the §12
arguments use the principal-unit part); recorded in the b2-protocol log by the
orchestrator. -/
theorem cyclo_mem_cycloTower1 {a : ℕ} (ha : ¬ (p : ℕ) ∣ a) (hp2 : p ≠ 2)
    (ha1 : a ≡ 1 [MOD p]) :
    cyclo p ha hp2 ∈ cycloTower1 p := by
  intro n hn
  -- `(cyclo).elems n ∈ 𝒟_n`, hence in its closure and in `𝒰_n`
  have hmemD : (cyclo p ha hp2).elems n ∈ cycloUnits p n :=
    cyclo_elems_mem_cycloUnits p ha hp2 hn
  have hmemloc : (cyclo p ha hp2).elems n ∈ localUnits p n :=
    globalUnits_le_localUnits p n (cycloUnits_le_globalUnits p n hmemD)
  -- the underlying value is `c_n(a)`
  have hval : ((cyclo p ha hp2).elems n : ℂ_[p]) = cycloUnit p a n := by
    change ((if hn : 1 ≤ n then Units.mk0 (cycloUnit p a n)
      (cycloUnit_ne_zero p ha hn) else 1 : ℂ_[p]ˣ) : ℂ_[p]) = _
    rw [dif_pos hn, Units.val_mk0]
  rw [cycloClosureOne, Subgroup.mem_inf]
  refine ⟨?_, ?_⟩
  · rw [cycloClosure, Subgroup.mem_inf]
    exact ⟨Subgroup.le_topologicalClosure _ hmemD, hmemloc⟩
  · rw [mem_localUnitsOne_iff]
    refine ⟨hmemloc, ?_⟩
    rw [hval]
    exact norm_cycloUnit_sub_one_lt_one p ha hn ha1

theorem cyclo_mem_unitsTower1 {a : ℕ} (ha : ¬ (p : ℕ) ∣ a) (hp2 : p ≠ 2)
    (ha1 : a ≡ 1 [MOD p]) :
    cyclo p ha hp2 ∈ unitsTower1 p :=
  cycloTower1_le_unitsTower1 p (cyclo_mem_cycloTower1 p ha hp2 ha1)

/-! ## The Tate twist `ℤ_p(1)` sits inside the cyclotomic tower (RJW §12.5, the
injectivity sub-lemma)

The systems `(ξ_n^a)_n` of `ℤ_p(1)` are limits of the integral powers `(ξ_n^k)_k` of the
cyclotomic root of unity `ξ_n`. Each `ξ_n^k` is a cyclotomic unit lying in `𝒰_{n,1}`
(`‖ξ_n^k − 1‖ < 1`, RJW: a power of the uniformiser's root of unity is principal), so the
continuous `ℤ_p`-power `ξ_n^a = zpPow ξ_n a` lands in the p-adic closure `𝒞_{n,1}`. This
is the inclusion `ℤ_p(1) ⊆ 𝒞_{∞,1}` used in the injectivity half of the image
computation. -/

/-- `ξ_{p^n} ≠ 0` (a nonzero root of unity). -/
private theorem zetaSys_ne_zero' {n : ℕ} : zetaSys p n ≠ 0 :=
  norm_ne_zero_iff.mp (by
    rw [norm_primitiveRoot_eq_one' p (zetaSys_primitiveRoot p n)]; exact one_ne_zero)

/-- `ξ_{p^n}` as a unit of `ℂ_[p]ˣ` (a nonzero root of unity). -/
private noncomputable def zetaSysU {n : ℕ} (_hn : 1 ≤ n) : ℂ_[p]ˣ :=
  Units.mk0 (zetaSys p n) (zetaSys_ne_zero' p)

private theorem zetaSysU_val {n : ℕ} (hn : 1 ≤ n) : (zetaSysU p hn : ℂ_[p]) = zetaSys p n :=
  Units.val_mk0 _

/-- `‖ξ_{p^n} − 1‖ < 1`: the root of unity is a principal unit (`= ‖π_n‖ < 1`). -/
private theorem norm_zetaSys_sub_one_lt_one' {n : ℕ} (hn : 1 ≤ n) :
    ‖zetaSys p n - 1‖ < 1 := by
  have := norm_pi_lt_one p hn; rwa [pi] at this

/-- `ξ_{p^n}^k ∈ 𝒟_n` (the integral power of the root of unity is a cyclotomic unit):
its value `ξ_n^k ∈ closure(cycloGenSet)` (a power of the generator `ξ_n`) and it is a
global unit (a root of unity is integral with integral inverse, and lies in `F_n`). -/
private theorem zetaSysU_pow_mem_cycloUnits {n : ℕ} (hn : 1 ≤ n) (k : ℕ) :
    zetaSysU p hn ^ k ∈ cycloUnits p n := by
  rw [cycloUnits, Subgroup.mem_inf]
  have hgen : zetaSysU p hn ∈ cycloGenSet p n := Or.inl (zetaSysU_val p hn)
  refine ⟨Subgroup.pow_mem _ (Subgroup.subset_closure hgen) k, ?_, ?_, ?_⟩
  · -- `ξ_n^k ∈ F_n`
    rw [Units.val_pow_eq_pow_val, zetaSysU_val]
    exact pow_mem (IntermediateField.mem_adjoin_simple_self ℚ _) k
  · -- `ξ_n^k` integral over `ℤ`
    rw [Units.val_pow_eq_pow_val, zetaSysU_val]
    exact ((zetaSys_primitiveRoot p n).isIntegral (pow_pos hp.out.pos n)).pow k
  · -- `(ξ_n^k)⁻¹ = (ξ_n⁻¹)^k` integral over `ℤ` (`ξ_n⁻¹ = ξ_n^{p^n−1}` is a root of unity)
    rw [show (((zetaSysU p hn ^ k)⁻¹ : ℂ_[p]ˣ) : ℂ_[p]) = ((zetaSys p n)⁻¹) ^ k from by
      rw [Units.val_inv_eq_inv_val, Units.val_pow_eq_pow_val, zetaSysU_val, inv_pow]]
    refine IsIntegral.pow ?_ k
    -- `ξ_n⁻¹ = ξ_n^{p^n − 1}`, an integral power
    rw [show (zetaSys p n)⁻¹ = (zetaSys p n) ^ (p ^ n - 1) from ?_]
    · exact ((zetaSys_primitiveRoot p n).isIntegral (pow_pos hp.out.pos n)).pow _
    · refine inv_eq_of_mul_eq_one_left ?_
      rw [← pow_succ, Nat.sub_add_cancel (Nat.one_le_pow _ _ hp.out.pos),
        (zetaSys_primitiveRoot p n).pow_eq_one]

/-- `ξ_{p^n}` is a principal local unit: `ξ_n ∈ 𝒰_{n,1}` (norm `1`, `≡ 1 mod 𝔭_n`). -/
private theorem zetaSysU_mem_localUnitsOne {n : ℕ} (hn : 1 ≤ n) :
    zetaSysU p hn ∈ localUnitsOne p n := by
  have hξ1 : ‖zetaSys p n‖ = 1 := norm_primitiveRoot_eq_one' p (zetaSys_primitiveRoot p n)
  have hmemO : (zetaSysU p hn : ℂ_[p]) ∈ O p n := by
    rw [zetaSysU_val, O, Subring.mem_inf]; exact ⟨zetaSys_mem_K p n, le_of_eq hξ1⟩
  have hinvval : (((zetaSysU p hn)⁻¹ : ℂ_[p]ˣ) : ℂ_[p]) = (zetaSys p n)⁻¹ := by
    rw [Units.val_inv_eq_inv_val, zetaSysU_val]
  have hinvnorm : ‖(zetaSys p n)⁻¹‖ ≤ 1 := le_of_eq (by rw [norm_inv, hξ1, inv_one])
  have hmemOinv : (((zetaSysU p hn)⁻¹ : ℂ_[p]ˣ) : ℂ_[p]) ∈ O p n := by
    rw [hinvval, O, Subring.mem_inf]
    exact ⟨(K p n).inv_mem (zetaSys_mem_K p n), hinvnorm⟩
  rw [mem_localUnitsOne_iff]
  exact ⟨⟨hmemO, hmemOinv⟩, by rw [zetaSysU_val]; exact norm_zetaSys_sub_one_lt_one' p hn⟩

/-- The `ℤ_p`-power `ξ_{p^n}^a = zpPow ξ_n a` of the root of unity lands in `𝒞_{n,1}`:
it is a continuous image of `ℤ_p` agreeing with the integral powers `ξ_n^k ∈ 𝒟_n` on
the (dense) naturals, so it lies in the p-adic closure `(𝒟_n)⁻`; and it is a principal
unit (`zpPow_mem_localUnitsOne`, `ξ_n ∈ 𝒰_{n,1}`). -/
theorem zpPow_zetaSys_mem_cycloClosureOne {n : ℕ} (hn : 1 ≤ n) (a : ℤ_[p])
    {x : ℂ_[p]ˣ} (hx : (x : ℂ_[p]) = zpPow p (zetaSys p n) a) :
    x ∈ cycloClosureOne p n := by
  have hz1 : ‖zetaSys p n - 1‖ < 1 := norm_zetaSys_sub_one_lt_one' p hn
  -- continuity of `c ↦ zpPow ξ_n c`
  have hcont : Continuous (zpPow p (zetaSys p n)) := by
    have h : zpPow p (zetaSys p n) = (PadicInt.addChar_of_value_at_one (zetaSys p n - 1)
        (tendsto_pow_atTop_nhds_zero_iff_norm_lt_one.mpr hz1) : ℤ_[p] → ℂ_[p]) := by
      funext c; rw [zpPow, dif_pos (tendsto_pow_atTop_nhds_zero_iff_norm_lt_one.mpr hz1)]
    rw [h]; exact PadicInt.continuous_addChar_of_value_at_one _
  -- the continuous unit-power `F : ℤ_[p] → ℂ_[p]ˣ`, `F c = ⟨ξ_n^c, ξ_n^{−c}⟩`
  set F : ℤ_[p] → ℂ_[p]ˣ := fun c => ⟨zpPow p (zetaSys p n) c, zpPow p (zetaSys p n) (-c),
    by rw [← zpPow_add p hz1, add_neg_cancel, show (0 : ℤ_[p]) = ((0 : ℕ) : ℤ_[p]) by norm_cast,
      zpPow_natCast p hz1, pow_zero],
    by rw [← zpPow_add p hz1, neg_add_cancel, show (0 : ℤ_[p]) = ((0 : ℕ) : ℤ_[p]) by norm_cast,
      zpPow_natCast p hz1, pow_zero]⟩ with hF
  have hFval : ∀ c, (F c : ℂ_[p]) = zpPow p (zetaSys p n) c := fun _ => rfl
  have hFcont : Continuous F :=
    Units.continuous_iff.2 ⟨hcont, hcont.comp continuous_neg⟩
  -- `F (k : ℕ) = ξu^k` (matches the integral powers)
  have hFnat : ∀ k : ℕ, F (k : ℤ_[p]) = zetaSysU p hn ^ k := by
    intro k
    refine Units.ext ?_
    rw [hFval, zpPow_natCast p hz1, Units.val_pow_eq_pow_val, zetaSysU_val]
  -- `x = F a` and `range F ⊆ closure(↑𝒟_n)`, so `x ∈ (𝒟_n)⁻`
  have hxF : x = F a := Units.ext (by rw [hFval]; exact hx)
  have hclos : x ∈ (cycloUnits p n).topologicalClosure := by
    -- `F a ∈ closure(↑𝒟_n)` by density of `ℕ ↪ ℤ_[p]` and `F(ℕ) ⊆ 𝒟_n`
    have hrange : Set.range F ⊆ closure (cycloUnits p n : Set ℂ_[p]ˣ) := by
      -- `range F = F '' (closure (range cast)) ⊆ closure (F '' range cast) = closure {ξu^k}`
      have h1 : Set.range F = F '' (closure (Set.range (Nat.cast : ℕ → ℤ_[p]))) := by
        rw [PadicInt.denseRange_natCast.closure_range, Set.image_univ]
      rw [h1]
      refine (image_closure_subset_closure_image hFcont).trans (closure_mono ?_)
      rw [← Set.range_comp]
      rintro _ ⟨k, rfl⟩
      show (F ∘ Nat.cast) k ∈ (cycloUnits p n : Set ℂ_[p]ˣ)
      rw [Function.comp_apply, hFnat k]
      exact zetaSysU_pow_mem_cycloUnits p hn k
    have : x ∈ closure (cycloUnits p n : Set ℂ_[p]ˣ) := by rw [hxF]; exact hrange ⟨a, rfl⟩
    rwa [← Subgroup.topologicalClosure_coe, SetLike.mem_coe] at this
  -- the principal-unit part comes from `zpPow_mem_localUnitsOne` at `ξ_n ∈ 𝒰_{n,1}`
  obtain ⟨v, hvval, hvmem⟩ := zpPow_mem_localUnitsOne p (zetaSysU_mem_localUnitsOne p hn) a
  have hxv : x = v := Units.ext (by rw [hx, hvval, zetaSysU_val])
  rw [cycloClosureOne, Subgroup.mem_inf, cycloClosure, Subgroup.mem_inf]
  exact ⟨⟨hclos, by rw [hxv]; exact hvmem.1⟩, by rw [hxv]; exact hvmem⟩

/-! ## The closure `𝒞_{n,1}` is a `ℤ_p`-module — the §13 `(p−1)`-rootedness (RJW lem:closure,
TeX 3503–3505 / lem:global generators 2)

The topological closure `(𝒟_n)⁻` of the cyclotomic units is closed under the binomial
`ℤ_p`-action `zpPow` on principal units: it is a *closed* subgroup, the unit-power map
`a ↦ y^a` is continuous and sends the dense naturals into the (sub)group, so the whole
`ℤ_p`-orbit lands back in the closure. Combined with the invertibility of `p−1 ∈ ℤ_p^×`
(`p−1 ≡ −1 mod p`, `PadicInt.norm_natCast_p_sub_one`), every principal unit whose
`(p−1)`-th power lies in `𝒞_{n,1}` lies in `𝒞_{n,1}` itself — the unique `(p−1)`-th root
`g = (g^{p−1})^{(p−1)⁻¹}` stays in the `zpPow`-closed closure. This is precisely the
`ℤ_p`-module/closure layer feeding `wGamma_mem_cycloTower1` (RJW LemmaGeneratorCinfty1). -/

/-- **The closure `(𝒟_n)⁻` is `zpPow`-closed** (RJW lem:closure, TeX 3503): if a principal
unit `y` lies in the topological closure of the cyclotomic units, so does every `ℤ_p`-power
`y^a = zpPow y a`. Same density argument as `zpPow_zetaSys_mem_cycloClosureOne`: the
continuous unit-power map `F c = ⟨y^c, y^{−c}⟩` sends the dense naturals to `y^k ∈ (𝒟_n)⁻`
(a subgroup), so its range lies in the closed `(𝒟_n)⁻`. -/
theorem zpPow_mem_cycloUnits_topologicalClosure {n : ℕ} {y : ℂ_[p]ˣ}
    (hyc : ‖(y : ℂ_[p]) - 1‖ < 1) (hyclos : y ∈ (cycloUnits p n).topologicalClosure)
    (a : ℤ_[p]) {x : ℂ_[p]ˣ} (hx : (x : ℂ_[p]) = zpPow p (y : ℂ_[p]) a) :
    x ∈ (cycloUnits p n).topologicalClosure := by
  -- continuity of `c ↦ zpPow y c`
  have hcont : Continuous (zpPow p (y : ℂ_[p])) := by
    have h : zpPow p (y : ℂ_[p]) = (PadicInt.addChar_of_value_at_one ((y : ℂ_[p]) - 1)
        (tendsto_pow_atTop_nhds_zero_iff_norm_lt_one.mpr hyc) : ℤ_[p] → ℂ_[p]) := by
      funext c; rw [zpPow, dif_pos (tendsto_pow_atTop_nhds_zero_iff_norm_lt_one.mpr hyc)]
    rw [h]; exact PadicInt.continuous_addChar_of_value_at_one _
  -- continuous unit-power map `F c = ⟨y^c, y^{−c}⟩`
  set F : ℤ_[p] → ℂ_[p]ˣ := fun c => ⟨zpPow p (y : ℂ_[p]) c, zpPow p (y : ℂ_[p]) (-c),
    by rw [← zpPow_add p hyc, add_neg_cancel, show (0 : ℤ_[p]) = ((0 : ℕ) : ℤ_[p]) by norm_cast,
      zpPow_natCast p hyc, pow_zero],
    by rw [← zpPow_add p hyc, neg_add_cancel, show (0 : ℤ_[p]) = ((0 : ℕ) : ℤ_[p]) by norm_cast,
      zpPow_natCast p hyc, pow_zero]⟩ with hF
  have hFval : ∀ c, (F c : ℂ_[p]) = zpPow p (y : ℂ_[p]) c := fun _ => rfl
  have hFcont : Continuous F := Units.continuous_iff.2 ⟨hcont, hcont.comp continuous_neg⟩
  have hFnat : ∀ k : ℕ, F (k : ℤ_[p]) = y ^ k := by
    intro k; refine Units.ext ?_
    rw [hFval, zpPow_natCast p hyc, Units.val_pow_eq_pow_val]
  have hxF : x = F a := Units.ext (by rw [hFval]; exact hx)
  -- `range F ⊆ closure ↑(𝒟_n)⁻`: density of `ℕ ↪ ℤ_[p]` and `F(ℕ) ⊆ (𝒟_n)⁻`
  have hrange : Set.range F ⊆ closure ((cycloUnits p n).topologicalClosure : Set ℂ_[p]ˣ) := by
    have h1 : Set.range F = F '' (closure (Set.range (Nat.cast : ℕ → ℤ_[p]))) := by
      rw [PadicInt.denseRange_natCast.closure_range, Set.image_univ]
    rw [h1]
    refine (image_closure_subset_closure_image hFcont).trans (closure_mono ?_)
    rw [← Set.range_comp]
    rintro _ ⟨k, rfl⟩
    show (F ∘ Nat.cast) k ∈ ((cycloUnits p n).topologicalClosure : Set ℂ_[p]ˣ)
    rw [Function.comp_apply, hFnat k]
    exact pow_mem hyclos k
  have hxmem : x ∈ closure ((cycloUnits p n).topologicalClosure : Set ℂ_[p]ˣ) := by
    rw [hxF]; exact hrange ⟨a, rfl⟩
  rwa [(Subgroup.isClosed_topologicalClosure _).closure_eq, SetLike.mem_coe] at hxmem

/-- **`𝒞_{n,1}` is uniquely `(p−1)`-rooted** (RJW lem:global generators 2): a principal unit
`g ∈ 𝒰_{n,1}` whose `(p−1)`-th power lies in the closure `𝒞_{n,1}` lies in `𝒞_{n,1}` itself.
Since `p−1 ∈ ℤ_p^×` (`PadicInt.norm_natCast_p_sub_one`), `g = (g^{p−1})^{(p−1)⁻¹}` is a
`zpPow`-power of the closure element `g^{p−1}`, hence in the `zpPow`-closed closure component
(`zpPow_mem_cycloUnits_topologicalClosure`); the local/principal components are inherited from
`g ∈ 𝒰_{n,1}`. This is the `ℤ_p`-module/closure layer of `wGamma_mem_cycloTower1`. -/
theorem mem_cycloClosureOne_of_pow_mem {n : ℕ} {g : ℂ_[p]ˣ}
    (hg : g ∈ localUnitsOne p n) (hgpow : g ^ (p - 1) ∈ cycloClosureOne p n) :
    g ∈ cycloClosureOne p n := by
  have hgc : ‖(g : ℂ_[p]) - 1‖ < 1 := ((mem_localUnitsOne_iff p).1 hg).2
  -- `g^{p−1} ∈ (𝒟_n)⁻`
  have hgpowclos : g ^ (p - 1) ∈ (cycloUnits p n).topologicalClosure := by
    rw [cycloClosureOne, Subgroup.mem_inf, cycloClosure, Subgroup.mem_inf] at hgpow
    exact hgpow.1.1
  -- `p−1 ∈ ℤ_p^×`; `c` its inverse
  have hunit : IsUnit ((p - 1 : ℕ) : ℤ_[p]) :=
    PadicInt.isUnit_iff.mpr PadicInt.norm_natCast_p_sub_one
  obtain ⟨c, hc⟩ := hunit.exists_left_inv
  -- `g = zpPow (g^{p−1}) c` (the unique `(p−1)`-th root via the binomial action)
  have hgeq : (g : ℂ_[p]) = zpPow p ((g ^ (p - 1) : ℂ_[p]ˣ) : ℂ_[p]) c := by
    rw [Units.val_pow_eq_pow_val]
    have hpow : (g : ℂ_[p]) ^ (p - 1) = zpPow p (g : ℂ_[p]) ((p - 1 : ℕ) : ℤ_[p]) :=
      (zpPow_natCast p hgc (p - 1)).symm
    rw [hpow, ← zpPow_mul p hgc, mul_comm, hc,
      show (1 : ℤ_[p]) = ((1 : ℕ) : ℤ_[p]) by norm_cast, zpPow_natCast p hgc, pow_one]
  have hypowc : ‖((g ^ (p - 1) : ℂ_[p]ˣ) : ℂ_[p]) - 1‖ < 1 := by
    rw [Units.val_pow_eq_pow_val, ← zpPow_natCast p hgc]
    exact norm_zpPow_sub_one_lt_one p hgc _
  -- `g` is in each of the three components of `𝒞_{n,1}`
  rw [cycloClosureOne, Subgroup.mem_inf, cycloClosure, Subgroup.mem_inf]
  exact ⟨⟨zpPow_mem_cycloUnits_topologicalClosure p hypowc hgpowclos c hgeq,
    ((mem_localUnitsOne_iff p).1 hg).1⟩, hg⟩

end Coleman

end PadicLFunctions
