import VersoBlueprint

/-!  Shared KaTeX macro prelude for every blueprint chapter.

All chapters import this module and must NOT declare their own `tex_prelude`:
per-module preludes are snapshotted into a single shared key of
`window.bpTexPreludeTable` at render time, so divergent per-chapter macro sets
silently overwrite each other (raw `\CC`/`\roi` in the rendered site).
One identical shared chunk makes the overwrite harmless. -/

open Informal

tex_prelude r#"\def\Z{\mathbb{Z}}\def\Q{\mathbb{Q}}\def\R{\mathbb{R}}\def\C{\mathbb{C}}\def\N{\mathbb{N}}\def\F{\mathbb{F}}\def\Zp{\mathbb{Z}_p}\def\Qp{\mathbb{Q}_p}\def\Cp{\mathbb{C}_p}\def\Fp{\mathbb{F}_p}\def\Zpx{\mathbb{Z}_p^{\times}}\def\Qpx{\mathbb{Q}_p^{\times}}\def\Qbar{\overline{\mathbb{Q}}}\def\Qpbar{\overline{\mathbb{Q}_p}}\def\cO{\mathcal{O}}\def\cC{\mathcal{C}}\def\cH{\mathcal{H}}\def\cG{\mathcal{G}}\def\cN{\mathcal{N}}\def\cM{\mathcal{M}}\def\cD{\mathcal{D}}\def\cA{\mathcal{A}}\def\sX{\mathscr{X}}\def\sY{\mathscr{Y}}\def\sM{\mathscr{M}}\def\sL{\mathscr{L}}\def\sU{\mathscr{U}}\def\sW{\mathscr{W}}\def\sE{\mathscr{E}}\def\sV{\mathscr{V}}\def\sG{\mathscr{G}}\def\Gal{\mathrm{Gal}}\def\Frob{\mathrm{Frob}}\def\Lam{\Lambda}\def\Teich{\omega}\def\ord{\mathrm{ord}}\def\val{\mathrm{val}}\def\res{\operatorname{res}}\def\Res{\operatorname{Res}}\def\Tr{\mathrm{Tr}}\def\Nm{\mathrm{N}}\def\Mahler{\mathfrak{M}}\def\Mellin{\mathrm{Mel}}\def\Exp{\mathrm{Exp}}\def\Col{\mathrm{Col}}\def\Log{\mathrm{Log}}\def\charid{\mathrm{char}}\def\cores{\mathrm{cores}}\def\loc{\mathrm{loc}}\def\Iw{\mathrm{Iw}}\def\GG{\mathscr{G}}\def\abs#1{\left\lvert#1\right\rvert}\def\norm#1{\left\lVert#1\right\rVert}\def\ang#1{\left\langle#1\right\rangle}\def\set#1{\left\{#1\right\}}\def\floor#1{\left\lfloor#1\right\rfloor}\def\cW{\mathcal{W}}\def\uhp{\mathcal{H}}\def\Am{\mathscr{A}}\def\sC{\mathscr{C}}\def\eps{\varepsilon}\def\mua{\mu_a}\def\zetap{\zeta_p}\def\DD{\mathscr{D}}\def\CC{\mathscr{C}}\def\WW{\mathscr{W}}\def\dlog{\partial\log}\def\xip{\xi_{p^n}}\def\pri{\mathfrak{p}}\def\sA{\mathscr{A}}\def\UU{\mathscr{U}}\def\VV{\mathscr{V}}\def\Cl{\mathrm{Cl}}\def\Fn{F_\infty}\def\fa{f_a}\def\Fa{F_a}\def\pa{\partial}\def\sigmaa{\sigma_a}\def\thetaa{\theta_a}\def\cF{\mathcal{F}}\def\cL{\mathcal{L}}\def\sD{\mathscr{D}}\def\Fil{\mathrm{Fil}}\def\Hom{\mathrm{Hom}}\def\Im{\mathrm{Im}}\def\Gr{\mathrm{Gr}}\def\defeq{:=}\def\Bcris{\mathbf{B}_{\mathrm{cris}}}\def\cClc{\mathscr{C}^{\mathrm{lc}}}\def\sMlc{\mathscr{M}^{\mathrm{lc}}}\def\cCla{\mathscr{C}^{\mathrm{la}}}\def\sDla{\mathscr{D}^{\mathrm{la}}}\def\binomc#1#2{\left(\!\begin{array}{c}#1\\#2\end{array}\!\right)}\def\rp{\mathscr{R}^{+}}\def\vp{v_p}\def\vC{v_{\mathscr{C}}}\def\OL{\mathscr{O}_L}\def\one{\mathbf{1}}\def\GL{\mathrm{GL}}\def\A{\mathbb{A}}\def\ch{\mathrm{ch}}\def\HIw{\mathrm{H}^1_{\mathrm{Iw}}}\def\Hone{\mathrm{H}^1}\def\Homc{\mathrm{Hom}_{\mathrm{cts}}}\def\roi{\mathcal{O}}\def\Rep{\mathrm{Rep}}\def\Dcris{\mathbf{D}_{\mathrm{cris}}}\def\Sha{\text{Ш}}\def\rk{\mathrm{rk}}\def\Gaminf{\Gamma}\def\Rp{\mathscr{R}^{+}}\def\zp{\zeta_p}\def\zpi{\zeta_{p,i}}\def\Fat{\widetilde{F}_a}\def\logp{\log_p}\def\dpartial{\partial}\def\sR{\mathscr{R}}\def\Li{\mathrm{Li}}\def\GGam{\Gamma}\def\GCal{\mathcal{G}}\def\Char{\mathrm{Char}}\def\Ch{\mathrm{Ch}}\def\varprojlim{\mathop{\underleftarrow{\lim}}}\def\varinjlim{\mathop{\underrightarrow{\lim}}}"#
