/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import PadicLFunctions.IwasawaProof.GaloisAction
import PadicLFunctions.Iwasawa.CyclotomicUnits
import PadicLFunctions.Iwasawa.ZetaGalois

/-!
# Generators for the cyclotomic units (RJW §12.3–12.4, TeX 3450–3578) — E12.4

The conjugation-fixed units `γ_{n,a} = ξ^{(1−a)/2} c_n(a) ∈ 𝒟_n^+`; the global generator
lemmas (`lem:cyc units gen`, `cor:cyc units gen 2`); the closure lemma
(`lem:closure`, p-adic closure of a `ℤ`-span = `ℤ_p`-span); and `LemmaGeneratorCinfty1`
(`𝒞_{∞,1}^+` cyclic over `Λ(𝒢^+)`, generated by `(wγ_{n,a})_n`). This cluster natively
resolves the §11 b2-logged `a ≡ 1 mod p` note: `w ∈ μ_{p−1}` is the Teichmüller
correction making `wγ_{n,a} ≡ 1 mod 𝔭_n`. Skeleton.
-/

open PadicLFunctions PadicLFunctions.Coleman

noncomputable section

namespace PadicLFunctions.Coleman

variable (p : ℕ) [hp : Fact p.Prime]

/-- **RJW TeX 3458**: the conjugation-fixed cyclotomic unit
`γ_{n,a} = ξ_{p^n}^{(1−a)/2} c_n(a)` (half-power via `(2 : ZMod (p^n))⁻¹`, `p` odd). -/
def gammaUnit (a n : ℕ) : ℂ_[p] := sorry

/-- `γ_{n,a} ∈ 𝒟_n^+` (conjugation-fixed, RJW TeX 3458–3459). -/
theorem gammaUnit_mem_cycloUnitsPlus {a : ℕ} (ha : ¬ (p : ℕ) ∣ a) (hp2 : p ≠ 2)
    {n : ℕ} (hn : 1 ≤ n) :
    ∃ g : ℂ_[p]ˣ, (g : ℂ_[p]) = gammaUnit p a n ∧ g ∈ cycloUnitsPlus p n := sorry

/-- **RJW lem:cyc units gen (i) (TeX 3461–3482)**: `𝒟_n^+` is generated by `−1` and the
`γ_{n,a}` with `(a,p)=1`. (`cor:cyc units gen 2`, TeX 3484–3486: a single `γ_{n,a}` with
`a` generating `(ℤ/p^nℤ)^×` suffices as a `ℤ[𝒢_n^+]`-module generator — its statement
needs the finite Galois action on units and is finalised in E12.4 at execution.) -/
theorem cycloUnitsPlus_eq_closure_gammas (hp2 : p ≠ 2) {n : ℕ} (hn : 1 ≤ n) :
    cycloUnitsPlus p n = Subgroup.closure
      ({g : ℂ_[p]ˣ | ∃ b : ℕ, ¬ (p : ℕ) ∣ b ∧ (g : ℂ_[p]) = gammaUnit p b n} ∪
        {g : ℂ_[p]ˣ | (g : ℂ_[p]) = -1}) := sorry

/-- **RJW lem:closure (TeX 3503–3505)**: for `g_1,…,g_r ∈ 𝒰_{n,1}`, the p-adic closure of
the multiplicative `ℤ`-span `⟨g_i⟩` is the `ℤ_p`-span (the `zpPow` binomial converges,
`ℤ_p^r` compact). Stated for a single generator `g` (the case used downstream). -/
theorem closure_zspan_eq_zpspan {n : ℕ} (hn : 1 ≤ n) {g : ℂ_[p]ˣ}
    (hg : g ∈ localUnitsOne p n)
    (x : ℂ_[p]ˣ) (hx : x ∈ (Subgroup.zpowers g).topologicalClosure) :
    ∃ a : ℤ_[p], (x : ℂ_[p]) = zpPow p (g : ℂ_[p]) a := sorry

/-- **RJW LemmaGeneratorCinfty1 (TeX 3553–3560)**: `𝒞_{∞,1}^+` is a cyclic
`Λ(𝒢^+)`-module generated by `(wγ_{n,a})_n`, where `a` is an integer topological
generator of `ℤ_p^×` and `w ∈ μ_{p−1}` with `aw ≡ 1 mod 𝔭_n` (the Teichmüller
correction making `wγ_{n,a} ≡ 1 mod 𝔭_n` — the §11 b2 note resolved). Stated as the
existence of a generating tower. -/
theorem cycloTower1Plus_cyclic_generator {a : ℕ} (ha : ¬ (p : ℕ) ∣ a) (hp2 : p ≠ 2)
    {u : NormCompatUnits p} (hu : u ∈ cycloTower1Plus p) :
    ∃ v : NormCompatUnits p, v ∈ cycloTower1Plus p ∧
      ∀ w : NormCompatUnits p, w ∈ cycloTower1Plus p →
        -- Λ(𝒢^+)-cyclicity shape; E12.4 finalises
        ∃ _μ : PadicMeasure p (PadicMeasure.GPlus p), True := sorry

end PadicLFunctions.Coleman
